/**
 * HandSystem - Hand of consumable cards with chain-recipe combos.
 *
 * Core mechanics:
 *   1. Hand stacks bottom-up (slot 0 = bottom). New drops fall to the
 *      lowest empty slot.
 *   2. When three consecutive same-defId cards sit in the stack they
 *      auto-merge into a single enhanced "merged" card at that slot.
 *   3. The player clicks a card to USE it. The card runs its single (or
 *      merged-enhanced) effect and is appended to the active CHAIN.
 *   4. After every use we re-scan the recipe book. Any recipe whose
 *      ingredient multiset is contained in the chain — and that has not
 *      already fired this chain — fires as an additional effect.
 *   5. The chain resets on a board action or on turn end.
 */

import { GameState } from '@core/GameState'
import { Card, CardType } from '@entities/Card'
import { Character } from '@entities/Character'
import { LANE_DISTANCE_COUNT } from '@entities/Lane'
import { HandCard, HandCardId, HandCardDefinition, HandEffectTargeting } from '@entities/HandCard'
import { getHandCardDef } from '@data/HandCards'
import { Recipe, RECIPES } from '@data/Recipes'
import { DropSystem } from './DropSystem'

export interface HandTarget {
  laneIndex: number
  distance: number
  card: Card
}

export interface FiredRecipe {
  recipe: Recipe
  /** Short message describing what the recipe did. */
  message: string
  /** Currency generated by recipe effects that pay shop money. */
  coinsGained?: number
}

/** Tracks a single card removed from the board so the UI can play its
 *  consume animation BEFORE the next render erases it. */
export interface RemovedFieldCard {
  cardId: string
  type: CardType
}

export interface HandUseResult {
  success: boolean
  /** Single-card effect message. */
  message: string
  /** Cards that auto-merged or were absorbed by a merge after this use. */
  mergeMessages: string[]
  /** Field cards removed by the single hand-card effect only. Recipe removals
   *  are reported by fireNextPendingRecipe after the UI delay. */
  removedFieldCards: RemovedFieldCard[]
  /** Currency gained by a coin hand card; UI applies it to the shop wallet. */
  coinsGained?: number
  /** Extra hand-gauge progress granted by the card's explicit effect. */
  gaugeCountBonus?: number
}

export interface RecipeFireResult {
  /** Recipes that fired after the chain-delay beat. */
  firedRecipes: FiredRecipe[]
  /** Field cards removed by those delayed recipe effects. */
  removedFieldCards: RemovedFieldCard[]
  /** Total shop currency generated by fired recipes. */
  coinsGained?: number
}

/**
 * The active chain. Lives on the GameState to survive hand re-renders. We
 * track:
 *   - sequence: defIds in the order they were physically used
 *   - firedRecipeIds: recipe ids already triggered for this chain
 */
export interface ChainState {
  sequence: HandCardId[]
  firedRecipeIds: Set<string>
}

interface RecipeEffectResult {
  /** Player-facing effect summary used by the log/banner. */
  message: string
  /** Optional shop money paid by this recipe. */
  coinsGained?: number
}

export class HandSystem {
  /** Build a fresh empty chain. */
  static newChain(): ChainState {
    return { sequence: [], firedRecipeIds: new Set() }
  }

  /** Reset the chain in-place (board action / turn end). */
  static resetChain(chain: ChainState): void {
    chain.sequence = []
    chain.firedRecipeIds = new Set()
  }

  /** Insert a freshly drawn drop into the hand at the bottom-most empty slot. */
  static enqueueDrop(character: Character, card: HandCard): boolean {
    const ok = character.addHandCard(card)
    if (ok) HandSystem.runAutoMerges(character)
    return ok
  }

  /** Snapshot every Card present on the field, keyed by id → type. Used to
   *  diff what got removed across an effect application so the UI can play
   *  consume animations on the right cells. */
  private static snapshotFieldCards(gs: GameState): Map<string, CardType> {
    const m = new Map<string, CardType>()
    for (const lane of gs.lanes) {
      for (let d = 0; d < LANE_DISTANCE_COUNT; d++) {
        const c = lane.getCardAtDistance(d)
        if (c) m.set(c.id, c.type)
      }
    }
    return m
  }

  /** Run a single use on slot `slotIndex`; recipe firing is delayed by index.ts. */
  static useSingle(
    gs: GameState,
    chain: ChainState,
    slotIndex: number,
    target?: HandTarget
  ): HandUseResult {
    const character = gs.character
    const card = character.hand[slotIndex]
    if (!card) {
      return { success: false, message: '비어 있는 슬롯', mergeMessages: [], removedFieldCards: [] }
    }
    const def = getHandCardDef(card.defId)
    if (!HandSystem.isValidTarget(def, target, card.merged === true)) {
      return {
        success: false,
        message: `${def.name}은(는) 조건에 맞는 대상을 골라야 해`,
        mergeMessages: [],
        removedFieldCards: [],
      }
    }

    // Snapshot the field BEFORE any mutation so we can diff removals after.
    const beforeField = HandSystem.snapshotFieldCards(gs)

    // Apply the card effect (merged cards use the enhanced version).
    const message = card.merged
      ? HandSystem.applyTripleEffect(gs, def, target)
      : HandSystem.applySingleEffect(gs, def, target)

    character.removeHandCardAt(slotIndex)

    // Extend the visible recipe chain with exactly one real card entry. The
    // `카드` item's combo-count text now means hand-gauge progress, not hidden
    // recipe ingredients, so recipes still read only this physical sequence.
    chain.sequence.push(card.defId)
    const gaugeCountBonus = HandSystem.gaugeCountBonusFor(card.defId, card.merged === true)
    if (gaugeCountBonus > 0) character.gainCandle(gaugeCountBonus)

    // Recipes are deliberately resolved later by fireNextPendingRecipe(), which
    // gives the UI a readable beat between the card effect and combo explosion.
    const mergeMessages = HandSystem.runAutoMerges(character)

    // The 10-slot gauge always advances once per played hand card. This is
    // gameplay flow, not per-card rules data, so the card definitions no longer
    // repeat a redundant candleGain value on every entry.
    character.gainCandle(1)

    // Diff the field snapshot to record removed cards for animation.
    const afterField = HandSystem.snapshotFieldCards(gs)
    const removedFieldCards: RemovedFieldCard[] = []
    for (const [id, type] of beforeField.entries()) {
      if (!afterField.has(id)) removedFieldCards.push({ cardId: id, type })
    }

    return {
      success: true,
      message,
      mergeMessages,
      removedFieldCards,
      coinsGained: card.defId === 'coin' ? (card.merged ? 5 : 1) : 0,
      gaugeCountBonus,
    }
  }

  /** Extra hand-gauge progress contributed by cards with combo-count effects. */
  private static gaugeCountBonusFor(defId: HandCardId, isMerged: boolean): number {
    if (defId !== 'card') return 0
    return isMerged ? 7 : 1
  }

  /** Recipe ingredient count of `id`; only physically played cards qualify. */
  private static countInChain(chain: ChainState, id: HandCardId): number {
    let n = 0
    for (const d of chain.sequence) if (d === id) n++
    return n
  }

  /** Recipe is contained in chain when each ingredient count is satisfied. */
  private static recipeMatches(recipe: Recipe, chain: ChainState): boolean {
    for (const [id, needed] of Object.entries(recipe.ingredients)) {
      if (!needed) continue
      if (HandSystem.countInChain(chain, id as HandCardId) < needed) return false
    }
    return true
  }

  /**
   * Return every not-yet-fired recipe that would become active if `defId` were
   * used now. The renderer consumes this as a non-mutating hint source so recipe
   * glow rules stay tied to the same declarative recipe book as real gameplay.
   */
  static previewTriggeredRecipes(
    chain: ChainState,
    defId: HandCardId,
    _isMerged: boolean = false
  ): Recipe[] {
    const preview: ChainState = {
      sequence: [...chain.sequence, defId],
      firedRecipeIds: new Set(chain.firedRecipeIds),
    }
    // Recipe hints intentionally mirror physical ingredient rules, not gauge
    // progress: one `카드` preview must not promise `셔플`.
    return RECIPES.filter((recipe) => {
      if (preview.firedRecipeIds.has(recipe.id)) return false
      return HandSystem.recipeMatches(recipe, preview)
    })
  }

  /** Check whether the current chain has at least one newly satisfied recipe. */
  static hasPendingRecipe(chain: ChainState): boolean {
    for (const recipe of RECIPES) {
      if (chain.firedRecipeIds.has(recipe.id)) continue
      if (HandSystem.recipeMatches(recipe, chain)) return true
    }
    return false
  }

  /** Fire exactly one pending recipe so the UI can compact/refill between combo beats. */
  static fireNextPendingRecipe(gs: GameState, chain: ChainState): RecipeFireResult {
    const beforeField = HandSystem.snapshotFieldCards(gs)
    const firedRecipe = HandSystem.fireNextMatchedRecipe(gs, chain)
    const afterField = HandSystem.snapshotFieldCards(gs)
    const removedFieldCards: RemovedFieldCard[] = []
    for (const [id, type] of beforeField.entries()) {
      if (!afterField.has(id)) removedFieldCards.push({ cardId: id, type })
    }
    const firedRecipes = firedRecipe ? [firedRecipe] : []
    return { firedRecipes, removedFieldCards, coinsGained: firedRecipe?.coinsGained ?? 0 }
  }

  private static fireNextMatchedRecipe(gs: GameState, chain: ChainState): FiredRecipe | null {
    // Sort by ingredient size ascending so smaller recipes resolve first.
    const sorted = [...RECIPES].sort((a, b) => a.totalCount - b.totalCount)
    for (const recipe of sorted) {
      if (chain.firedRecipeIds.has(recipe.id)) continue
      if (!HandSystem.recipeMatches(recipe, chain)) continue
      const effect = HandSystem.applyRecipeEffect(gs, recipe)
      chain.firedRecipeIds.add(recipe.id)
      return { recipe, message: effect.message, coinsGained: effect.coinsGained }
    }
    return null
  }

  /** Apply a recipe's effect against the GameState. */
  private static applyRecipeEffect(gs: GameState, recipe: Recipe): RecipeEffectResult {
    const c = gs.character
    switch (recipe.effect) {
      case 'gain-wax-drop': {
        const gained = c.hasHandRoom() ? c.addHandCard(DropSystem.makeCard('wax-drop')) : false
        if (gained) HandSystem.runAutoMerges(c)
        return { message: gained ? '촛농 1장 획득' : '손패가 가득 차 촛농 획득 실패' }
      }
      case 'damage-all-field-enemies-1':
        return { message: HandSystem.damageEnemies(gs, 'field', 1) }
      case 'gain-coin-1':
        return { message: '+1$', coinsGained: 1 }
      case 'draw-random-hand-1': {
        const gained = c.hasHandRoom() ? c.addHandCard(DropSystem.generateDrop()) : false
        if (gained) HandSystem.runAutoMerges(c)
        return { message: gained ? '랜덤 손패 1장 획득' : '손패가 가득 차 드로우 실패' }
      }
      case 'destroy-random-front-enemy':
        return { message: HandSystem.destroyRandomFrontEnemy(gs) }
      case 'convert-random-hazard-to-treasure':
        return { message: HandSystem.convertRandomHazardToTreasure(gs) }
      case 'collect-random-treasure':
        return { message: HandSystem.collectRandomTreasure(gs, c) }
      case 'convert-random-waiting-to-treasure':
        return { message: HandSystem.convertRandomWaitingSlotToTreasure(gs) }
      case 'clear-all-field-cards': {
        const cleared = HandSystem.clearAllOfTypes(gs, [
          CardType.ENEMY,
          CardType.TRAP,
          CardType.TREASURE,
        ])
        return { message: `필드 ${cleared}장 제거` }
      }
      case 'damage-front-enemies-3':
        return { message: HandSystem.damageEnemies(gs, 'front', 3) }
      case 'clear-front-cards':
        return { message: HandSystem.clearFrontCards(gs) }
      case 'collect-waiting-treasures':
        return { message: HandSystem.collectWaitingTreasures(gs, c) }
      case 'damage-front-enemies-2':
        return { message: HandSystem.damageEnemies(gs, 'front', 2) }
    }
  }

  /** Apply a hand card's single-use effect. Returns a short message. */
  private static applySingleEffect(
    gs: GameState,
    def: HandCardDefinition,
    target?: HandTarget
  ): string {
    const c = gs.character
    switch (def.id) {
      case 'wax-drop': {
        const healed = c.heal(1)
        return `체력 +${healed}`
      }
      case 'candle': {
        const shielded = c.addShield(1)
        return `방패 +${shielded}`
      }
      case 'ember':
        return HandSystem.damageTargetEnemy(gs, target, 2)
      case 'key':
        return HandSystem.collectRandomTreasure(gs, c)
      case 'wax':
        return HandSystem.freezeTarget(target, 1)
      case 'match': {
        const gained = c.gainEmber(1)
        return `불씨 카운트 +${gained}`
      }
      case 'holy-water':
        return HandSystem.cleanseRandomField(gs, 2)
      case 'chitin':
        return HandSystem.removeTargetTrap(gs, target)
      case 'card':
        return '손패 콤보 카운트 +1'
      case 'coin':
        return '+1$'
    }
  }

  /** Apply the enhanced merged-card effect. */
  private static applyTripleEffect(
    gs: GameState,
    def: HandCardDefinition,
    target?: HandTarget
  ): string {
    const c = gs.character
    switch (def.id) {
      case 'wax-drop': {
        const healed = c.heal(5)
        return `트리플 체력 +${healed}`
      }
      case 'candle': {
        const shielded = c.addShield(5)
        return `트리플 방패 +${shielded}`
      }
      case 'ember':
        return HandSystem.damageTargetEnemy(gs, target, 10)
      case 'key':
        return HandSystem.collectAllTreasures(gs, c)
      case 'wax':
        return HandSystem.freezeFrontCards(gs, 3)
      case 'match': {
        const gained = c.gainEmber(5)
        return `트리플 불씨 카운트 +${gained}`
      }
      case 'holy-water':
        return HandSystem.cleanseAllField(gs)
      case 'chitin': {
        const cleared = HandSystem.clearAllOfTypes(gs, [CardType.TRAP])
        return `트리플 함정 ${cleared}장 제거`
      }
      case 'card':
        return '트리플 손패 콤보 카운트 +7'
      case 'coin':
        return '+5$'
    }
  }

  /** Scan the hand for runs of three consecutive same-defId cards. */
  static runAutoMerges(character: Character): string[] {
    const messages: string[] = []
    let didChange = true
    let safety = 32
    while (didChange && safety-- > 0) {
      didChange = false
      const hand = character.hand
      for (let i = 0; i + 2 < hand.length; i++) {
        const a = hand[i]
        const b = hand[i + 1]
        const c = hand[i + 2]
        if (!a || !b || !c) continue
        // Already-merged cards do not stack into another merged card; otherwise
        // a flood of duplicates could chain into massive auto-effects.
        if (a.merged || b.merged || c.merged) continue
        if (a.defId === b.defId && b.defId === c.defId) {
          const def = getHandCardDef(a.defId)
          // Splice 3 → 1 merged card at slot i.
          hand.splice(i, 3, {
            uid: `${a.defId}-merged-${a.uid}`,
            defId: a.defId,
            merged: true,
          })
          messages.push(`${def.name} ×3 자동 합성`)
          didChange = true
          break
        }
      }
    }
    return messages
  }

  /** Validate per-card targeting rules before consuming the hand card. */
  private static isValidTarget(
    def: HandCardDefinition,
    target: HandTarget | undefined,
    isMerged: boolean
  ): boolean {
    // Some triple effects become broad field effects and no longer need the
    // single-card target used by the base effect.
    const rule = isMerged ? def.targeting.triple : def.targeting.base
    if (rule.selection !== 'target') return true
    if (!target) return false
    return HandSystem.targetMatchesRule(rule, target)
  }

  /** Check a selected board card against the shared hand-card targeting table. */
  private static targetMatchesRule(rule: HandEffectTargeting, target: HandTarget): boolean {
    if (rule.zone === 'front' && target.distance !== 0) return false
    if (rule.zone === 'waiting' && target.distance === 0) return false
    if (rule.zone !== 'front' && rule.zone !== 'waiting' && rule.zone !== 'field') return false

    if (rule.filter === 'enemy') return target.card.type === CardType.ENEMY
    if (rule.filter === 'trap') return target.card.type === CardType.TRAP
    if (rule.filter === 'treasure') return target.card.type === CardType.TREASURE
    if (rule.filter === 'enemy-or-treasure') {
      return target.card.type === CardType.ENEMY || target.card.type === CardType.TREASURE
    }
    if (rule.filter === 'hazard')
      return target.card.type === CardType.TRAP || target.card.isFrozen()
    if (rule.filter === 'any') return true
    return false
  }

  /** Deal damage to a chosen field enemy, or to the first enemy for merged auto-use. */
  private static damageTargetEnemy(
    gs: GameState,
    target: HandTarget | undefined,
    amount: number
  ): string {
    const actualTarget = target ?? HandSystem.findFirstOnField(gs, [CardType.ENEMY])
    if (!actualTarget || actualTarget.card.type !== CardType.ENEMY) return '대상 적 없음'
    actualTarget.card.takeDamage(amount)
    if (actualTarget.card.getHealth() <= 0) {
      gs.removeCardFromRow(actualTarget.card, actualTarget.distance)
      return `${actualTarget.card.name} 피해 ${amount}로 처치`
    }
    return `${actualTarget.card.name} 피해 ${amount}`
  }

  /** Damage enemies in either the whole field or only the active front row. */
  private static damageEnemies(gs: GameState, scope: 'front' | 'field', amount: number): string {
    const seen = new Set<Card>()
    let hit = 0
    let defeated = 0
    for (let lane = 0; lane < gs.lanes.length; lane++) {
      const maxDistance = scope === 'front' ? 1 : LANE_DISTANCE_COUNT
      for (let d = 0; d < maxDistance; d++) {
        const card = gs.lanes[lane].getCardAtDistance(d)
        if (!card || seen.has(card) || card.type !== CardType.ENEMY) continue
        seen.add(card)
        card.takeDamage(amount)
        hit++
        if (card.getHealth() <= 0) {
          gs.removeCardFromRow(card, d)
          defeated++
        }
      }
    }
    const scopeLabel = scope === 'front' ? '전방 적' : '필드 적'
    return `${scopeLabel} ${hit}체에 피해 ${amount}${defeated > 0 ? ` · ${defeated}체 처치` : ''}`
  }

  /** Destroy one random enemy from the active row. */
  private static destroyRandomFrontEnemy(gs: GameState): string {
    const enemies: { card: Card; distance: number }[] = []
    const seen = new Set<Card>()
    for (const lane of gs.lanes) {
      const card = lane.getCardAtDistance(0)
      if (!card || seen.has(card) || card.type !== CardType.ENEMY) continue
      seen.add(card)
      enemies.push({ card, distance: 0 })
    }
    if (enemies.length === 0) return '전방 적 없음'
    const pick = enemies[Math.floor(Math.random() * enemies.length)]
    gs.removeCardFromRow(pick.card, pick.distance)
    return `${pick.card.name} 처치`
  }

  /** Create a one-cell treasure card for recipe conversions. */
  private static makeRecipeTreasure(): Card {
    return new Card(
      `treasure-recipe-${Date.now()}-${Math.random()}`,
      CardType.TREASURE,
      '작은 상자',
      '1 item reward chest'
    )
  }

  /** Replace one unique field card with a treasure while preserving its row width. */
  private static replaceCardWithTreasure(gs: GameState, source: Card, distance: number): void {
    const treasure = HandSystem.makeRecipeTreasure()
    treasure.groupCount = Math.max(1, source.groupCount)
    for (let laneIndex = 0; laneIndex < gs.lanes.length; laneIndex++) {
      if (gs.lanes[laneIndex].getCardAtDistance(distance) === source) {
        gs.lanes[laneIndex].setCardAtDistance(distance, treasure)
      }
    }
  }

  /** MVP hazard conversion maps curse/mold wording to traps and frozen cards. */
  private static convertRandomHazardToTreasure(gs: GameState): string {
    const candidates: { card: Card; distance: number }[] = []
    const seen = new Set<Card>()
    for (const lane of gs.lanes) {
      for (let d = 0; d < LANE_DISTANCE_COUNT; d++) {
        const card = lane.getCardAtDistance(d)
        if (!card || seen.has(card)) continue
        if (card.type === CardType.TRAP || card.isFrozen()) {
          seen.add(card)
          candidates.push({ card, distance: d })
        }
      }
    }
    if (candidates.length === 0) return '변환할 함정/저주/곰팡이 없음'
    const pick = candidates[Math.floor(Math.random() * candidates.length)]
    HandSystem.replaceCardWithTreasure(gs, pick.card, pick.distance)
    return `${pick.card.name} 보물상자로 변환`
  }

  /** Turn one non-treasure waiting-line cell into a chest, including empty cells. */
  private static convertRandomWaitingSlotToTreasure(gs: GameState): string {
    const candidates: { laneIndex: number; distance: number; card: Card | null }[] = []
    for (let laneIndex = 0; laneIndex < gs.lanes.length; laneIndex++) {
      for (let d = 1; d < LANE_DISTANCE_COUNT; d++) {
        const card = gs.lanes[laneIndex].getCardAtDistance(d)
        if (card?.type === CardType.TREASURE) continue
        candidates.push({ laneIndex, distance: d, card })
      }
    }
    if (candidates.length === 0) return '대기라인에 변환할 칸 없음'
    const pick = candidates[Math.floor(Math.random() * candidates.length)]
    gs.lanes[pick.laneIndex].setCardAtDistance(pick.distance, HandSystem.makeRecipeTreasure())
    return pick.card ? `${pick.card.name} 보물상자로 변환` : '빈 대기칸을 보물상자로 변환'
  }

  /** Remove every active-row card, counting unique card instances once. */
  private static clearFrontCards(gs: GameState): string {
    const seen = new Set<Card>()
    let cleared = 0
    for (let lane = 0; lane < gs.lanes.length; lane++) {
      const card = gs.lanes[lane].getCardAtDistance(0)
      if (!card || seen.has(card)) continue
      seen.add(card)
      gs.removeCardFromRow(card, 0)
      cleared++
    }
    return `전방 ${cleared}장 제거`
  }

  /** Open only treasures that are still waiting behind the active row. */
  private static collectWaitingTreasures(gs: GameState, character: Character): string {
    const treasures: { card: Card; distance: number }[] = []
    const seen = new Set<Card>()
    for (let lane = 0; lane < gs.lanes.length; lane++) {
      for (let d = 1; d < LANE_DISTANCE_COUNT; d++) {
        const card = gs.lanes[lane].getCardAtDistance(d)
        if (!card || seen.has(card) || card.type !== CardType.TREASURE) continue
        seen.add(card)
        treasures.push({ card, distance: d })
      }
    }
    let gained = 0
    for (const treasure of treasures) {
      gained += HandSystem.awardTreasureDrops(character, treasure.card)
      gs.removeCardFromRow(treasure.card, treasure.distance)
    }
    HandSystem.runAutoMerges(character)
    return `대기 보물 ${treasures.length}개 획득: 손패 ${gained}장`
  }

  /** Open one random treasure chest and convert its width into item drops. */
  private static collectRandomTreasure(gs: GameState, character: Character): string {
    const treasures = HandSystem.collectAllOfType(gs, CardType.TREASURE)
    if (treasures.length === 0) return '보물상자 없음'
    const pick = treasures[Math.floor(Math.random() * treasures.length)]
    const gained = HandSystem.awardTreasureDrops(character, pick)
    for (let d = 0; d < LANE_DISTANCE_COUNT; d++) gs.removeCardFromRow(pick, d)
    return `${pick.name} 획득: 손패 ${gained}장`
  }

  /** Open every treasure currently on the 3×3 field. */
  private static collectAllTreasures(gs: GameState, character: Character): string {
    const treasures = HandSystem.collectAllOfType(gs, CardType.TREASURE)
    let gained = 0
    for (const treasure of treasures) {
      gained += HandSystem.awardTreasureDrops(character, treasure)
      for (let d = 0; d < LANE_DISTANCE_COUNT; d++) gs.removeCardFromRow(treasure, d)
    }
    HandSystem.runAutoMerges(character)
    return `트리플 보물 ${treasures.length}개 획득: 손패 ${gained}장`
  }

  /** Award item drops based on chest width: 1/3/5, matching ActionSystem. */
  private static awardTreasureDrops(character: Character, treasure: Card): number {
    const safeSpan = Math.max(1, Math.min(3, treasure.groupCount))
    const dropCount = safeSpan === 1 ? 1 : safeSpan === 2 ? 3 : 5
    let gained = 0
    for (let i = 0; i < dropCount; i++) {
      if (!character.hasHandRoom()) break
      character.addHandCard(DropSystem.generateDrop())
      gained++
    }
    HandSystem.runAutoMerges(character)
    return gained
  }

  /** Apply wax hardening to a selected front card. */
  private static freezeTarget(target: HandTarget | undefined, turns: number): string {
    if (!target) return '굳힐 대상 없음'
    target.card.freeze(turns)
    return `${target.card.name} ${turns}턴 굳음`
  }

  /** Apply wax hardening to every front enemy/treasure. */
  private static freezeFrontCards(gs: GameState, turns: number): string {
    const seen = new Set<Card>()
    let count = 0
    for (const lane of gs.lanes) {
      const card = lane.getCardAtDistance(0)
      if (!card || seen.has(card)) continue
      if (card.type !== CardType.ENEMY && card.type !== CardType.TREASURE) continue
      seen.add(card)
      card.freeze(turns)
      count++
    }
    return `전방 ${count}장 ${turns}턴 굳음`
  }

  /** Cleanse random field debuffs. MVP maps curse/mold cleanup to trap removal and wax removal. */
  private static cleanseRandomField(gs: GameState, count: number): string {
    const candidates = HandSystem.collectAllOfType(gs, CardType.TRAP).map((card) => ({ card }))
    const frozenCards = HandSystem.collectAllFieldCards(gs).filter((card) => card.isFrozen())
    frozenCards.forEach((card) => candidates.push({ card }))
    let cleansed = 0
    while (candidates.length > 0 && cleansed < count) {
      const pickIndex = Math.floor(Math.random() * candidates.length)
      const [{ card }] = candidates.splice(pickIndex, 1)
      if (card.type === CardType.TRAP) {
        for (let d = 0; d < LANE_DISTANCE_COUNT; d++) gs.removeCardFromRow(card, d)
      } else {
        card.frozenTurns = 0
      }
      cleansed++
    }
    return `정화 ${cleansed}장`
  }

  /** Cleanse every MVP debuff/trap from the field. */
  private static cleanseAllField(gs: GameState): string {
    const traps = HandSystem.clearAllOfTypes(gs, [CardType.TRAP])
    let thawed = 0
    for (const card of HandSystem.collectAllFieldCards(gs)) {
      if (!card.isFrozen()) continue
      card.frozenTurns = 0
      thawed++
    }
    return `트리플 전체 정화: 함정 ${traps}장, 굳음 ${thawed}장 해제`
  }

  /** Remove the selected front trap. */
  private static removeTargetTrap(gs: GameState, target: HandTarget | undefined): string {
    if (!target || target.card.type !== CardType.TRAP) return '제거할 전방 함정 없음'
    gs.removeCardFromRow(target.card, target.distance)
    return `${target.card.name} 제거`
  }

  /** Find the first matching card anywhere on the 3×3 field. */
  private static findFirstOnField(
    gs: GameState,
    types: CardType[]
  ): { card: Card; laneIndex: number; distance: number } | null {
    for (let laneIndex = 0; laneIndex < gs.lanes.length; laneIndex++) {
      for (let distance = 0; distance < LANE_DISTANCE_COUNT; distance++) {
        const card = gs.lanes[laneIndex].getCardAtDistance(distance)
        if (card && types.includes(card.type)) return { card, laneIndex, distance }
      }
    }
    return null
  }

  /** Collect unique Card instances from the whole field. */
  private static collectAllFieldCards(gs: GameState): Card[] {
    const out: Card[] = []
    const seen = new Set<Card>()
    for (const lane of gs.lanes) {
      for (let d = 0; d < LANE_DISTANCE_COUNT; d++) {
        const card = lane.getCardAtDistance(d)
        if (!card || seen.has(card)) continue
        seen.add(card)
        out.push(card)
      }
    }
    return out
  }

  private static collectAllOfType(gs: GameState, type: CardType): Card[] {
    const out: Card[] = []
    const seen = new Set<Card>()
    for (const lane of gs.lanes) {
      for (let d = 0; d < LANE_DISTANCE_COUNT; d++) {
        const card = lane.getCardAtDistance(d)
        if (!card || seen.has(card)) continue
        if (card.type === type) {
          seen.add(card)
          out.push(card)
        }
      }
    }
    return out
  }

  private static clearAllOfTypes(gs: GameState, types: CardType[]): number {
    const seen = new Set<Card>()
    let count = 0
    for (const lane of gs.lanes) {
      for (let d = 0; d < LANE_DISTANCE_COUNT; d++) {
        const card = lane.getCardAtDistance(d)
        if (!card || seen.has(card)) continue
        if (types.includes(card.type)) {
          seen.add(card)
          gs.removeCardFromRow(card, d)
          count++
        }
      }
    }
    return count
  }
}
