/**
 * HandSystem - Hand of consumable cards with chain-recipe combos.
 *
 * Core mechanics:
 *   1. Hand stacks bottom-up (slot 0 = bottom). New drops fall to the
 *      lowest empty slot.
 *   2. When three consecutive same-defId cards sit in the stack they
 *      auto-merge into a single enhanced "merged" card at that slot.
 *   3. The player clicks a card to USE it. The card runs its single (or
 *      merged-enhanced) effect and is appended to the active CHAIN.
 *   4. After every use we re-scan the recipe book. Any recipe whose
 *      ingredient multiset is contained in the chain — and that has not
 *      already fired this chain — fires as an additional effect.
 *   5. The chain resets on a board action or on turn end.
 */

import { GameState } from '@core/GameState'
import { Card, CardType } from '@entities/Card'
import { Character } from '@entities/Character'
import { LANE_DISTANCE_COUNT } from '@entities/Lane'
import { HandCard, HandCardId, HandCardDefinition, HandEffectTargeting } from '@entities/HandCard'
import { getHandCardDef } from '@data/HandCards'
import { Recipe, RECIPES } from '@data/Recipes'
import { DropSystem } from './DropSystem'

export interface HandTarget {
  laneIndex: number
  distance: number
  card: Card
}

export interface FiredRecipe {
  recipe: Recipe
  /** Short message describing what the recipe did. */
  message: string
  /** Currency generated by recipe effects that pay shop money. */
  coinsGained?: number
  /** defId of a hand card drawn by this specific recipe, if any. */
  drawnHandCardDefId?: HandCardId
}

/** Tracks a single card removed from the board so the UI can play its
 *  consume animation BEFORE the next render erases it. */
export interface RemovedFieldCard {
  cardId: string
  type: CardType
}

export interface HandUseResult {
  success: boolean
  /** Single-card effect message. */
  message: string
  /** Cards that auto-merged or were absorbed by a merge after this use. */
  mergeMessages: string[]
  /** Field cards removed by the single hand-card effect only. Recipe removals
   *  are reported by fireNextPendingRecipe after the UI delay. */
  removedFieldCards: RemovedFieldCard[]
  /** Currency gained by a coin hand card; UI applies it to the shop wallet. */
  coinsGained?: number
  /** Extra hand-gauge progress granted by the card's explicit effect. */
  gaugeCountBonus?: number
  /** 탐욕의 동전: 사용자가 즉시 받는 피해. UI가 애니메이션과 함께 적용한다. */
  selfDamage?: number
  /** 탐욕의 동전: 획득 불빛 base값. UI(index.ts)가 인플레이션을 적용해 합산한다. */
  lightGained?: number
  /** 레바테인: index.ts가 피해 적용 전에 runSimulatedEnemyPhase()를 이 횟수만큼 실행한다. */
  simulatedBattlePhases?: number
  /** 레바테인: 시뮬레이션 이후 대상 카드에 입힐 피해량. index.ts가 takeDamage로 적용한다. */
  levateainDamage?: number
}

export interface RecipeFireResult {
  /** Recipes that fired after the chain-delay beat. */
  firedRecipes: FiredRecipe[]
  /** Field cards removed by those delayed recipe effects. */
  removedFieldCards: RemovedFieldCard[]
  /** Total shop currency generated by fired recipes. */
  coinsGained?: number
  /** Hand-card defIds drawn by recipes such as 셔플 (draw-random-hand-1).
   *  The UI logs each as an item-gain row so any "card drawn" feels
   *  consistent whether the source is a rail drop, the gauge, or a recipe. */
  drawnHandCardDefIds?: HandCardId[]
}

/**
 * The active chain. Lives on the GameState to survive hand re-renders. We
 * track:
 *   - sequence: defIds in the order they were physically used
 *   - firedRecipeIds: recipe ids already triggered for this chain
 */
export interface ChainState {
  sequence: HandCardId[]
  firedRecipeIds: Set<string>
}

interface RecipeEffectResult {
  /** Player-facing effect summary used by the log/banner. */
  message: string
  /** Optional shop money paid by this recipe. */
  coinsGained?: number
  /** defId of a hand card drawn by this recipe, if any. */
  drawnHandCardDefId?: HandCardId
}

export class HandSystem {
  /** 탐욕의 동전 사용 시 받는 자해 피해. */
  static readonly GREED_COIN_SELF_DAMAGE = 3
  /** 탐욕의 동전 불빛 base값(30층 1칸 적 처치의 약 절반). index.ts가 인플레이션을 적용한다. */
  static readonly GREED_COIN_LIGHT_BASE = 36

  /** Build a fresh empty chain. */
  static newChain(): ChainState {
    return { sequence: [], firedRecipeIds: new Set() }
  }

  /** Reset the chain in-place (board action / turn end). */
  static resetChain(chain: ChainState): void {
    chain.sequence = []
    chain.firedRecipeIds = new Set()
  }

  /** Insert a freshly drawn drop into the hand at the bottom-most empty slot. */
  static enqueueDrop(character: Character, card: HandCard): boolean {
    const ok = character.addHandCard(card)
    if (ok) HandSystem.runAutoMerges(character)
    return ok
  }

  /** Snapshot every Card present on the field, keyed by id → type. Used to
   *  diff what got removed across an effect application so the UI can play
   *  consume animations on the right cells. */
  private static snapshotFieldCards(gs: GameState): Map<string, CardType> {
    const m = new Map<string, CardType>()
    for (const lane of gs.lanes) {
      for (let d = 0; d < LANE_DISTANCE_COUNT; d++) {
        const c = lane.getCardAtDistance(d)
        if (c) m.set(c.id, c.type)
      }
    }
    return m
  }

  /** Run a single use on slot `slotIndex`; recipe firing is delayed by index.ts.
   *  `deferAutoMerge`로 트리플 자동 합성을 미루면, UI가 손패 이동/낙하 연출이 끝난 뒤
   *  별도 비트로 합성 연출을 재생할 수 있다(이동·합성 애니메이션 충돌 방지). */
  static useSingle(
    gs: GameState,
    chain: ChainState,
    slotIndex: number,
    target?: HandTarget,
    deferAutoMerge: boolean = false
  ): HandUseResult {
    const character = gs.character
    const card = character.hand[slotIndex]
    if (!card) {
      return { success: false, message: '비어 있는 슬롯', mergeMessages: [], removedFieldCards: [] }
    }
    const def = getHandCardDef(card.defId)
    if (!HandSystem.isValidTarget(def, target, card.merged === true)) {
      return {
        success: false,
        message: `${def.name}은(는) 조건에 맞는 대상을 골라야 해`,
        mergeMessages: [],
        removedFieldCards: [],
      }
    }

    // Snapshot the field BEFORE any mutation so we can diff removals after.
    const beforeField = HandSystem.snapshotFieldCards(gs)

    // Apply the card effect (merged cards use the enhanced version).
    const message = card.merged
      ? HandSystem.applyTripleEffect(gs, def, target)
      : HandSystem.applySingleEffect(gs, def, target)

    character.removeHandCardAt(slotIndex)

    // Extend the visible recipe chain with exactly one real card entry. The
    // `카드` item's combo-count text now means hand-gauge progress, not hidden
    // recipe ingredients, so recipes still read only this physical sequence.
    chain.sequence.push(card.defId)
    const baseGaugeBonus = HandSystem.gaugeCountBonusFor(card.defId, card.merged === true)
    const extraGaugeBonus = card.defId === 'card'
      ? (card.merged
          ? (gs.enhancements.tripleBonus['card'] ?? 0)
          : (gs.enhancements.singleBonus['card'] ?? 0))
      : 0
    const gaugeCountBonus = baseGaugeBonus + extraGaugeBonus
    if (gaugeCountBonus > 0) character.gainCandle(gaugeCountBonus)

    // Recipes are deliberately resolved later by fireNextPendingRecipe(), which
    // gives the UI a readable beat between the card effect and combo explosion.
    // deferAutoMerge면 합성을 미뤄 두고, index.ts가 손패 이동 연출 뒤 runAutoMerges를 직접 호출한다.
    const mergeMessages = deferAutoMerge ? [] : HandSystem.runAutoMerges(character)

    // 카드를 쓰면 콤보 게이지가 오른다. 3장이 합쳐진 트리플 카드는 3장을 한 번에 쓴
    // 셈이므로 +3, 일반 카드는 +1. (card 카드의 전용 게이지 효과는 위 gaugeCountBonus로 별도 가산)
    character.gainCandle(card.merged ? 3 : 1)

    // Diff the field snapshot to record removed cards for animation.
    const afterField = HandSystem.snapshotFieldCards(gs)
    const removedFieldCards: RemovedFieldCard[] = []
    for (const [id, type] of beforeField.entries()) {
      if (!afterField.has(id)) removedFieldCards.push({ cardId: id, type })
    }

    return {
      success: true,
      message,
      mergeMessages,
      removedFieldCards,
      coinsGained: card.defId === 'coin'
        ? (card.merged
            ? 5 + (gs.enhancements.tripleBonus['coin'] ?? 0)
            : 1 + (gs.enhancements.singleBonus['coin'] ?? 0))
        : 0,
      gaugeCountBonus,
      // 자해 피해와 불빛은 UI가 애니메이션과 함께 적용한다(모델은 여기서 건드리지 않음).
      selfDamage: HandSystem.selfDamageFor(card.defId, card.merged === true),
      lightGained: card.defId === 'greed-coin' ? HandSystem.GREED_COIN_LIGHT_BASE : 0,
      // 레바테인: 시뮬레이션 페이즈 수 + % 피해량을 index.ts에 전달해 적 행동 뒤 적용하게 한다.
      simulatedBattlePhases: card.defId === 'levatein' ? (card.merged ? 1 : 2) : undefined,
      levateainDamage: card.defId === 'levatein'
        ? (card.merged
          ? Math.max(15, Math.floor((target?.card.enemyHealthTotal ?? 0) * 0.45))
          : Math.max(10, Math.floor((target?.card.enemyHealthTotal ?? 0) * 0.30)))
        : undefined,
    }
  }

  /** 카드별 자해 피해(UI가 애니메이션과 함께 적용). 탐욕의 동전·제물 양초가 사용한다. */
  private static selfDamageFor(defId: HandCardId, isMerged: boolean): number {
    if (defId === 'greed-coin') return HandSystem.GREED_COIN_SELF_DAMAGE
    // 제물 양초는 단일 사용에만 자해 2(트리플은 자해 없이 더 큰 피해).
    if (defId === 'sacrifice-candle' && !isMerged) return 2
    return 0
  }

  /** Extra hand-gauge progress contributed by cards with combo-count effects. */
  private static gaugeCountBonusFor(defId: HandCardId, isMerged: boolean): number {
    if (defId !== 'card') return 0
    return isMerged ? 7 : 1
  }

  /** Recipe ingredient count of `id`; only physically played cards qualify. */
  private static countInChain(chain: ChainState, id: HandCardId): number {
    let n = 0
    for (const d of chain.sequence) if (d === id) n++
    return n
  }

  /** Recipe is contained in chain when each ingredient count is satisfied. */
  private static recipeMatches(recipe: Recipe, chain: ChainState): boolean {
    for (const [id, needed] of Object.entries(recipe.ingredients)) {
      if (!needed) continue
      if (HandSystem.countInChain(chain, id as HandCardId) < needed) return false
    }
    return true
  }

  /**
   * Return every not-yet-fired recipe that would become active if `defId` were
   * used now. The renderer consumes this as a non-mutating hint source so recipe
   * glow rules stay tied to the same declarative recipe book as real gameplay.
   */
  static previewTriggeredRecipes(
    chain: ChainState,
    defId: HandCardId,
    _isMerged: boolean = false
  ): Recipe[] {
    const preview: ChainState = {
      sequence: [...chain.sequence, defId],
      firedRecipeIds: new Set(chain.firedRecipeIds),
    }
    // Recipe hints intentionally mirror physical ingredient rules, not gauge
    // progress: one `카드` preview must not promise `셔플`.
    return RECIPES.filter((recipe) => {
      if (preview.firedRecipeIds.has(recipe.id)) return false
      return HandSystem.recipeMatches(recipe, preview)
    })
  }

  /** Check whether the current chain has at least one newly satisfied recipe. */
  static hasPendingRecipe(chain: ChainState): boolean {
    for (const recipe of RECIPES) {
      if (chain.firedRecipeIds.has(recipe.id)) continue
      if (HandSystem.recipeMatches(recipe, chain)) return true
    }
    return false
  }

  /** Fire exactly one pending recipe so the UI can compact/refill between combo beats. */
  static fireNextPendingRecipe(gs: GameState, chain: ChainState): RecipeFireResult {
    const beforeField = HandSystem.snapshotFieldCards(gs)
    const firedRecipe = HandSystem.fireNextMatchedRecipe(gs, chain)
    const afterField = HandSystem.snapshotFieldCards(gs)
    const removedFieldCards: RemovedFieldCard[] = []
    for (const [id, type] of beforeField.entries()) {
      if (!afterField.has(id)) removedFieldCards.push({ cardId: id, type })
    }
    const firedRecipes = firedRecipe ? [firedRecipe] : []
    const drawnHandCardDefIds = firedRecipe?.drawnHandCardDefId
      ? [firedRecipe.drawnHandCardDefId]
      : undefined
    return {
      firedRecipes,
      removedFieldCards,
      coinsGained: firedRecipe?.coinsGained ?? 0,
      drawnHandCardDefIds,
    }
  }

  private static fireNextMatchedRecipe(gs: GameState, chain: ChainState): FiredRecipe | null {
    // Sort by ingredient size ascending so smaller recipes resolve first.
    const sorted = [...RECIPES].sort((a, b) => a.totalCount - b.totalCount)
    for (const recipe of sorted) {
      if (chain.firedRecipeIds.has(recipe.id)) continue
      if (!HandSystem.recipeMatches(recipe, chain)) continue
      const effect = HandSystem.applyRecipeEffect(gs, recipe)
      chain.firedRecipeIds.add(recipe.id)
      return {
        recipe,
        message: effect.message,
        coinsGained: effect.coinsGained,
        drawnHandCardDefId: effect.drawnHandCardDefId,
      }
    }
    return null
  }

  /** Apply a recipe's effect against the GameState. */
  private static applyRecipeEffect(gs: GameState, recipe: Recipe): RecipeEffectResult {
    const c = gs.character
    const rb = gs.enhancements.recipeBonus
    const bonus = rb[recipe.id] ?? 0

    // 보스 전투 중에는 필드 카드를 변형·수집하는 레시피가 일반 레일에 영향을 주면 안 된다.
    // 피해를 주는 레시피(damage-*)는 보스에게도 반영하므로 차단하지 않는다.
    const BOSS_BLOCKED_EFFECTS: ReadonlySet<Recipe['effect']> = new Set([
      'collect-random-treasure',
      'convert-random-waiting-to-treasure',
      'convert-random-hazard-to-treasure',
      'clear-all-field-cards',
      'collect-waiting-treasures',
    ])
    if (gs.bossBattleActive && BOSS_BLOCKED_EFFECTS.has(recipe.effect)) {
      return { message: '보스 전투 중 — 필드 효과 차단' }
    }

    switch (recipe.effect) {
      case 'gain-wax-drop': {
        if (!c.hasHandRoom()) return { message: '손패가 가득 차 촛농 획득 실패' }
        c.addHandCard(DropSystem.makeCard('wax-drop'))
        HandSystem.runAutoMerges(c)
        return { message: '촛농 1장 획득', drawnHandCardDefId: 'wax-drop' }
      }
      case 'damage-all-field-enemies-1':
        return { message: HandSystem.damageEnemies(gs, 'field', 1 + bonus) }
      case 'gain-coin-1': {
        const total = 1 + bonus
        return { message: `+${total}$`, coinsGained: total }
      }
      case 'draw-random-hand-1': {
        // 셔플 강화: bonus장 추가 드로우
        const count = 1 + bonus
        let lastId: HandCardId | undefined
        for (let i = 0; i < count; i++) {
          if (!c.hasHandRoom()) break
          const drop = DropSystem.generateDrop()
          c.addHandCard(drop)
          lastId = drop.defId
        }
        HandSystem.runAutoMerges(c)
        return lastId
          ? { message: `랜덤 손패 ${count}장 획득`, drawnHandCardDefId: lastId }
          : { message: '손패가 가득 차 드로우 실패' }
      }
      case 'destroy-random-front-enemy':
        return { message: HandSystem.destroyRandomFrontEnemy(gs) }
      case 'convert-random-hazard-to-treasure': {
        // 지뢰제거반 강화: bonus회 추가 변환
        const msgs: string[] = []
        for (let i = 0; i < 1 + bonus; i++) msgs.push(HandSystem.convertRandomHazardToTreasure(gs))
        return { message: msgs.join(' / ') }
      }
      case 'collect-random-treasure': {
        // 열쇠공 강화: bonus개 추가 획득
        const msgs: string[] = []
        for (let i = 0; i < 1 + bonus; i++) msgs.push(HandSystem.collectRandomTreasure(gs, c))
        return { message: msgs.join(' / ') }
      }
      case 'convert-random-waiting-to-treasure': {
        // 탐욕 강화: bonus칸 추가 변환
        const msgs: string[] = []
        for (let i = 0; i < 1 + bonus; i++) msgs.push(HandSystem.convertRandomWaitingSlotToTreasure(gs))
        return { message: msgs.join(' / ') }
      }
      case 'clear-all-field-cards': {
        // "필드의 모든 칸 제거" — 꽃 칸도 포함해 전부 제거한다(보스만 타입 미포함으로 면역).
        const cleared = HandSystem.clearAllOfTypes(gs, [
          CardType.ENEMY,
          CardType.TRAP,
          CardType.TREASURE,
          CardType.FLOWER,
        ])
        return { message: `필드 ${cleared}장 제거` }
      }
      case 'damage-front-enemies-3':
        return { message: HandSystem.damageEnemies(gs, 'front', 3 + bonus) }
      case 'clear-front-cards':
        return { message: HandSystem.clearFrontCards(gs) }
      case 'collect-waiting-treasures':
        return { message: HandSystem.collectWaitingTreasures(gs, c) }
      case 'damage-front-enemies-2':
        return { message: HandSystem.damageEnemies(gs, 'front', 2 + bonus) }
    }
  }

  /** Apply a hand card's single-use effect. coin/card 보너스는 use()에서 처리한다. */
  private static applySingleEffect(
    gs: GameState,
    def: HandCardDefinition,
    target?: HandTarget
  ): string {
    const c = gs.character
    const bonus = gs.enhancements.singleBonus[def.id] ?? 0
    switch (def.id) {
      case 'wax-drop': {
        const healed = c.heal(1 + bonus)
        return `체력 +${healed}`
      }
      case 'candle': {
        const shielded = c.addShield(1 + bonus)
        return `방패 +${shielded}`
      }
      case 'ember':
        return HandSystem.damageTargetEnemy(gs, target, 2 + bonus)
      case 'key':
        return HandSystem.collectRandomTreasure(gs, c)
      case 'wax':
        return HandSystem.freezeTarget(target, 1)
      case 'match': {
        const gained = c.gainEmber(1 + bonus)
        return `불씨 게이지 +${gained}`
      }
      case 'holy-water':
        return HandSystem.cleanseRandomSpores(gs, 2)
      case 'chitin':
        return HandSystem.removeTargetTrap(gs, target)
      case 'card':
        // gainCandle 보너스는 use()에서 gs.enhancements.singleBonus['card']로 처리.
        return `콤보 게이지 +${1 + bonus}`
      case 'coin':
        // coinsGained 보너스는 use()에서 처리.
        return `+${1 + bonus}$`
      case 'greed-coin':
        // 자해 피해/불빛은 use()의 selfDamage·lightGained로 보고되어 UI에서 처리한다.
        return `소량의 불빛 · 자해 ${HandSystem.GREED_COIN_SELF_DAMAGE}`
      case 'sacrifice-candle':
        // 자해 2는 use()의 selfDamage로 처리. 여기서는 선택 적 피해만 적용한다.
        return HandSystem.damageTargetEnemy(gs, target, 5 + bonus)
      case 'levatein':
        // 적 행동 시뮬레이션(2회)과 %HP 피해는 useSingle 반환값으로 index.ts에 위임한다.
        return '레바테인: 즉시 2턴 흐름 후 최대체력 30% 피해'
      case 'firework':
        return HandSystem.distributeDamageAmongEnemies(gs, 3 + bonus)
      case 'book-of-flames':
        return HandSystem.applyBookOfFlames(gs, target, 0, 1)
    }
  }

  /** Apply the enhanced merged-card effect. coin/card 보너스는 use()에서 별도 처리한다. */
  private static applyTripleEffect(
    gs: GameState,
    def: HandCardDefinition,
    target?: HandTarget
  ): string {
    const c = gs.character
    const bonus = gs.enhancements.tripleBonus[def.id] ?? 0
    switch (def.id) {
      case 'wax-drop': {
        const healed = c.heal(5 + bonus)
        return `트리플 체력 +${healed}`
      }
      case 'candle': {
        const shielded = c.addShield(5 + bonus)
        return `트리플 방패 +${shielded}`
      }
      case 'ember':
        return HandSystem.damageTargetEnemy(gs, target, 10 + bonus)
      case 'key':
        return HandSystem.collectAllTreasures(gs, c)
      case 'wax':
        return HandSystem.freezeFrontCards(gs, 3)
      case 'match': {
        const gained = c.gainEmber(5 + bonus)
        return `트리플 불씨 게이지 +${gained}`
      }
      case 'holy-water':
        return HandSystem.cleanseAllSpores(gs)
      case 'chitin': {
        // 트리플도 단일 대상이되 3칸 함정까지 제거 가능(폭 제한은 targeting.maxSpan).
        return HandSystem.removeTargetTrap(gs, target)
      }
      case 'card': {
        // gainCandle 호출은 use()에서 gs.enhancements를 직접 읽어 처리한다.
        const total = 7 + bonus
        return `트리플 콤보 게이지 +${total}`
      }
      case 'coin':
        // coinsGained는 use()에서 처리된다.
        return `+${5 + bonus}$`
      case 'greed-coin':
        // 탐욕의 동전은 트리플 합성되지 않으므로 이 분기는 실제로 도달하지 않는다.
        return `소량의 불빛 · 자해 ${HandSystem.GREED_COIN_SELF_DAMAGE}`
      case 'sacrifice-candle':
        // 트리플은 자해 없이 더 큰 피해만 입힌다.
        return HandSystem.damageTargetEnemy(gs, target, 7 + bonus)
      case 'levatein':
        // 적 행동 시뮬레이션(1회)과 %HP 피해는 useSingle 반환값으로 index.ts에 위임한다.
        return '레바테인: 즉시 1턴 흐름 후 최대체력 45% 피해'
      case 'firework':
        return HandSystem.distributeDamageAmongEnemies(gs, 12 + bonus)
      case 'book-of-flames':
        return HandSystem.applyBookOfFlames(gs, target, 3 + bonus, 3)
    }
  }

  /** Scan the hand for runs of three consecutive same-defId cards. */
  /** 연속 동일 비합체 3장이 있어 자동 합성이 대기 중인지(모델 변경 없이) 확인한다.
   *  UI가 이동/낙하 연출 뒤 합성 비트를 분리할지 판단하는 데 쓴다. */
  static hasPendingAutoMerge(character: Character): boolean {
    const hand = character.hand
    for (let i = 0; i + 2 < hand.length; i++) {
      const a = hand[i]
      const b = hand[i + 1]
      const c = hand[i + 2]
      if (!a || !b || !c) continue
      if (a.merged || b.merged || c.merged) continue
      // 탐욕의 동전은 합성되지 않는 찌꺼기 카드라 트리플 대기 판정에서 제외한다.
      if (a.defId === 'greed-coin') continue
      if (a.defId === b.defId && b.defId === c.defId) return true
    }
    return false
  }

  static runAutoMerges(character: Character): string[] {
    const messages: string[] = []
    let didChange = true
    let safety = 32
    while (didChange && safety-- > 0) {
      didChange = false
      const hand = character.hand
      for (let i = 0; i + 2 < hand.length; i++) {
        const a = hand[i]
        const b = hand[i + 1]
        const c = hand[i + 2]
        if (!a || !b || !c) continue
        // Already-merged cards do not stack into another merged card; otherwise
        // a flood of duplicates could chain into massive auto-effects.
        if (a.merged || b.merged || c.merged) continue
        // 탐욕의 동전은 트리플 합성되지 않는다 — 손패를 갉아먹는 찌꺼기로 남는다.
        if (a.defId === 'greed-coin') continue
        if (a.defId === b.defId && b.defId === c.defId) {
          const def = getHandCardDef(a.defId)
          // Splice 3 → 1 merged card at slot i.
          hand.splice(i, 3, {
            uid: `${a.defId}-merged-${a.uid}`,
            defId: a.defId,
            merged: true,
            // Keep the exact consumed instance ids on the merged card.
            // The UI uses them while the card is newly rendered to pull
            // previous DOM rects and move upper cards into the lower slot.
            mergeSourceUids: [a.uid, b.uid, c.uid],
          })
          messages.push(`${def.name} ×3 자동 합성`)
          didChange = true
          break
        }
      }
    }
    return messages
  }

  /** Validate per-card targeting rules before consuming the hand card. */
  private static isValidTarget(
    def: HandCardDefinition,
    target: HandTarget | undefined,
    isMerged: boolean
  ): boolean {
    // Some triple effects become broad field effects and no longer need the
    // single-card target used by the base effect.
    const rule = isMerged ? def.targeting.triple : def.targeting.base
    if (rule.selection !== 'target') return true
    if (!target) return false
    return HandSystem.targetMatchesRule(rule, target)
  }

  /** Check a selected board card against the shared hand-card targeting table. */
  private static targetMatchesRule(rule: HandEffectTargeting, target: HandTarget): boolean {
    if (rule.zone === 'front' && target.distance !== 0) return false
    if (rule.zone === 'waiting' && target.distance === 0) return false
    if (rule.zone !== 'front' && rule.zone !== 'waiting' && rule.zone !== 'field') return false

    // 폭 제한: 지정된 maxSpan(칸=groupCount)을 넘는 카드는 대상에서 제외한다(키틴 2칸/3칸 분기).
    if (rule.maxSpan != null && target.card.groupCount > rule.maxSpan) return false

    // 보스는 5번째 카드 종류지만 적 양식을 그대로 따라가 손패 적 타겟팅에도 매칭된다.
    if (rule.filter === 'enemy') return target.card.type === CardType.ENEMY || target.card.type === CardType.BOSS
    if (rule.filter === 'trap') return target.card.type === CardType.TRAP
    if (rule.filter === 'spore') {
      // 성수 전용 필터: 일반 함정/폭탄은 두고 번식 포자만 대상으로 삼는다.
      return target.card.type === CardType.TRAP && target.card.trapKind === 'spore'
    }
    if (rule.filter === 'treasure') return target.card.type === CardType.TREASURE
    if (rule.filter === 'enemy-or-treasure') {
      return target.card.type === CardType.ENEMY || target.card.type === CardType.BOSS || target.card.type === CardType.TREASURE
    }
    if (rule.filter === 'turn-timer') return HandSystem.isTurnTimerCard(target.card)
    if (rule.filter === 'hazard')
      return target.card.type === CardType.TRAP || target.card.isFrozen()
    if (rule.filter === 'any') return true
    return false
  }

  /** Deal damage to a chosen field enemy/boss, or to the first enemy-like card for merged auto-use. */
  private static damageTargetEnemy(
    gs: GameState,
    target: HandTarget | undefined,
    amount: number
  ): string {
    // BOSS도 적과 같은 양식의 5번째 카드 종류이므로 손패 적 타겟팅이 동일하게 닿는다.
    const actualTarget = target ?? HandSystem.findFirstOnField(gs, [CardType.ENEMY, CardType.BOSS])
    if (
      !actualTarget ||
      (actualTarget.card.type !== CardType.ENEMY && actualTarget.card.type !== CardType.BOSS)
    )
      return '대상 적 없음'
    actualTarget.card.takeDamage(amount)
    if (actualTarget.card.getHealth() <= 0) {
      // 보스는 lanes에 그대로 두고 격파 시퀀스(흔들→갈라짐→펑→흐릿 확대)가 element를
      // 그대로 잡아 시각화한 뒤 직접 정리한다. 일반 적은 즉시 제거.
      if (actualTarget.card.type !== CardType.BOSS) {
        gs.removeCardFromRow(actualTarget.card, actualTarget.distance)
      }
      return `${actualTarget.card.name} 피해 ${amount}로 처치`
    }
    return `${actualTarget.card.name} 피해 ${amount}`
  }

  /** Damage enemies/boss in either the whole field or only the active front row. */
  private static damageEnemies(gs: GameState, scope: 'front' | 'field', amount: number): string {
    const seen = new Set<Card>()
    let hit = 0
    let defeated = 0
    for (let lane = 0; lane < gs.lanes.length; lane++) {
      const maxDistance = scope === 'front' ? 1 : LANE_DISTANCE_COUNT
      for (let d = 0; d < maxDistance; d++) {
        const card = gs.lanes[lane].getCardAtDistance(d)
        if (!card || seen.has(card)) continue
        if (card.type !== CardType.ENEMY && card.type !== CardType.BOSS) continue
        seen.add(card)
        card.takeDamage(amount)
        hit++
        if (card.getHealth() <= 0) {
          // 보스는 별도 격파 시퀀스가 lanes 정리를 담당한다(시퀀스 도중 element가
          // 사라지지 않도록). 일반 적은 즉시 lane에서 제거.
          if (card.type !== CardType.BOSS) {
            gs.removeCardFromRow(card, d)
          }
          defeated++
        }
      }
    }
    const scopeLabel = scope === 'front' ? '전방 적' : '필드 적'
    return `${scopeLabel} ${hit}체에 피해 ${amount}${defeated > 0 ? ` · ${defeated}체 처치` : ''}`
  }

  /** 폭죽: 총 피해를 필드 적/보스에게 1점씩 무작위로 쪼개 분배한다.
   *  한 적에게 여러 점이 몰릴 수도, 여러 적에게 흩어질 수도 있다. */
  private static distributeDamageAmongEnemies(gs: GameState, total: number): string {
    // 살아 있는 적/보스 카드를 (대표 distance와 함께) 고유하게 모은다.
    const living: { card: Card; distance: number }[] = []
    const seen = new Set<Card>()
    for (let lane = 0; lane < gs.lanes.length; lane++) {
      for (let d = 0; d < LANE_DISTANCE_COUNT; d++) {
        const card = gs.lanes[lane].getCardAtDistance(d)
        if (!card || seen.has(card)) continue
        if (card.type !== CardType.ENEMY && card.type !== CardType.BOSS) continue
        seen.add(card)
        living.push({ card, distance: d })
      }
    }
    if (living.length === 0) return '대상 적 없음'

    let defeated = 0
    for (let i = 0; i < total && living.length > 0; i++) {
      const pickIndex = Math.floor(Math.random() * living.length)
      const entry = living[pickIndex]
      entry.card.takeDamage(1)
      if (entry.card.getHealth() <= 0) {
        // 보스는 lanes에 남겨 격파 시퀀스가 정리한다. 일반 적은 즉시 제거하고 후보에서 뺀다.
        if (entry.card.type !== CardType.BOSS) {
          gs.removeCardFromRow(entry.card, entry.distance)
        }
        living.splice(pickIndex, 1)
        defeated++
      }
    }
    return `폭죽: 적들에게 피해 ${total} 분배${defeated > 0 ? ` · ${defeated}체 처치` : ''}`
  }

  /** 화염의 서: (base + 누적 n) 피해를 선택 적에게 입히고, n을 increment만큼 영구 증가시킨다. */
  private static applyBookOfFlames(
    gs: GameState,
    target: HandTarget | undefined,
    base: number,
    increment: number
  ): string {
    const n = gs.enhancements.bookOfFlamesBonus ?? 0
    const amount = base + n
    const result = HandSystem.damageTargetEnemy(gs, target, amount)
    // 피해를 입힌 뒤 영구 누적값을 올린다(다음 사용부터 강해진다).
    gs.enhancements.bookOfFlamesBonus = n + increment
    return `${result} · 화염의 서 피해 영구 +${increment}(누적 ${gs.enhancements.bookOfFlamesBonus})`
  }

  /** Destroy one random enemy/boss from the active row. */
  private static destroyRandomFrontEnemy(gs: GameState): string {
    const enemies: { card: Card; distance: number }[] = []
    const seen = new Set<Card>()
    for (const lane of gs.lanes) {
      const card = lane.getCardAtDistance(0)
      if (!card || seen.has(card)) continue
      // 보스는 레시피 즉사 대상에서 제외 — 보스 면역 처리는 index.ts에서 저항 연출 담당.
      if (card.type !== CardType.ENEMY) continue
      seen.add(card)
      enemies.push({ card, distance: 0 })
    }
    if (enemies.length === 0) return '전방 적 없음'
    const pick = enemies[Math.floor(Math.random() * enemies.length)]
    gs.removeCardFromRow(pick.card, pick.distance)
    return `${pick.card.name} 처치`
  }

  /** Create a one-cell treasure card for recipe conversions. */
  private static makeRecipeTreasure(): Card {
    return new Card(
      `treasure-recipe-${Date.now()}-${Math.random()}`,
      CardType.TREASURE,
      '작은 상자',
      '1 item reward chest'
    )
  }

  /** Replace one unique field card with a treasure while preserving its row width. */
  private static replaceCardWithTreasure(gs: GameState, source: Card, distance: number): void {
    const treasure = HandSystem.makeRecipeTreasure()
    treasure.groupCount = Math.max(1, source.groupCount)
    for (let laneIndex = 0; laneIndex < gs.lanes.length; laneIndex++) {
      if (gs.lanes[laneIndex].getCardAtDistance(distance) === source) {
        gs.lanes[laneIndex].setCardAtDistance(distance, treasure)
      }
    }
  }

  /** MVP hazard conversion maps curse/mold wording to traps and frozen cards. */
  private static convertRandomHazardToTreasure(gs: GameState): string {
    const candidates: { card: Card; distance: number }[] = []
    const seen = new Set<Card>()
    for (const lane of gs.lanes) {
      for (let d = 0; d < LANE_DISTANCE_COUNT; d++) {
        const card = lane.getCardAtDistance(d)
        if (!card || seen.has(card)) continue
        if (card.type === CardType.TRAP || card.isFrozen()) {
          seen.add(card)
          candidates.push({ card, distance: d })
        }
      }
    }
    if (candidates.length === 0) return '변환할 함정/저주/곰팡이 없음'
    const pick = candidates[Math.floor(Math.random() * candidates.length)]
    HandSystem.replaceCardWithTreasure(gs, pick.card, pick.distance)
    return `${pick.card.name} 보물상자로 변환`
  }

  /** Turn one non-treasure waiting-line cell into a chest, including empty cells. */
  private static convertRandomWaitingSlotToTreasure(gs: GameState): string {
    const candidates: { laneIndex: number; distance: number; card: Card | null }[] = []
    for (let laneIndex = 0; laneIndex < gs.lanes.length; laneIndex++) {
      for (let d = 1; d < LANE_DISTANCE_COUNT; d++) {
        const card = gs.lanes[laneIndex].getCardAtDistance(d)
        if (card?.type === CardType.TREASURE) continue
        candidates.push({ laneIndex, distance: d, card })
      }
    }
    if (candidates.length === 0) return '대기라인에 변환할 칸 없음'
    const pick = candidates[Math.floor(Math.random() * candidates.length)]
    gs.lanes[pick.laneIndex].setCardAtDistance(pick.distance, HandSystem.makeRecipeTreasure())
    return pick.card ? `${pick.card.name} 보물상자로 변환` : '빈 대기칸을 보물상자로 변환'
  }

  /** Remove every active-row card, counting unique card instances once. */
  private static clearFrontCards(gs: GameState): string {
    const seen = new Set<Card>()
    let cleared = 0
    for (let lane = 0; lane < gs.lanes.length; lane++) {
      const card = gs.lanes[lane].getCardAtDistance(0)
      if (!card || seen.has(card)) continue
      // 보스는 전방 소멸 레시피에서 면역 — 저항 연출은 index.ts 레시피 루프에서 재생.
      if (card.type === CardType.BOSS) continue
      seen.add(card)
      gs.removeCardFromRow(card, 0)
      cleared++
    }
    return `전방 ${cleared}장 제거`
  }

  /** Open only treasures that are still waiting behind the active row. */
  private static collectWaitingTreasures(gs: GameState, character: Character): string {
    const treasures: { card: Card; distance: number }[] = []
    const seen = new Set<Card>()
    for (let lane = 0; lane < gs.lanes.length; lane++) {
      for (let d = 1; d < LANE_DISTANCE_COUNT; d++) {
        const card = gs.lanes[lane].getCardAtDistance(d)
        if (!card || seen.has(card) || card.type !== CardType.TREASURE) continue
        seen.add(card)
        treasures.push({ card, distance: d })
      }
    }
    let gained = 0
    for (const treasure of treasures) {
      gained += HandSystem.awardTreasureDrops(character, treasure.card)
      gs.removeCardFromRow(treasure.card, treasure.distance)
    }
    HandSystem.runAutoMerges(character)
    return `대기 보물 ${treasures.length}개 획득: 손패 ${gained}장`
  }

  /** Open one random treasure chest and convert its width into item drops. */
  private static collectRandomTreasure(gs: GameState, character: Character): string {
    const treasures = HandSystem.collectAllOfType(gs, CardType.TREASURE)
    if (treasures.length === 0) return '보물상자 없음'
    const pick = treasures[Math.floor(Math.random() * treasures.length)]
    const gained = HandSystem.awardTreasureDrops(character, pick)
    for (let d = 0; d < LANE_DISTANCE_COUNT; d++) gs.removeCardFromRow(pick, d)
    return `${pick.name} 획득: 손패 ${gained}장`
  }

  /** Open every treasure currently on the 3×3 field. */
  private static collectAllTreasures(gs: GameState, character: Character): string {
    const treasures = HandSystem.collectAllOfType(gs, CardType.TREASURE)
    let gained = 0
    for (const treasure of treasures) {
      gained += HandSystem.awardTreasureDrops(character, treasure)
      for (let d = 0; d < LANE_DISTANCE_COUNT; d++) gs.removeCardFromRow(treasure, d)
    }
    HandSystem.runAutoMerges(character)
    return `트리플 보물 ${treasures.length}개 획득: 손패 ${gained}장`
  }

  /** Award item drops based on chest width and kind, matching ActionSystem. */
  private static awardTreasureDrops(character: Character, treasure: Card): number {
    const safeSpan = Math.max(1, Math.min(3, treasure.groupCount))
    const dropCount = treasure.treasureKind === 'goldenChest'
      ? [3, 8, 15][safeSpan - 1]
      : safeSpan === 1 ? 1 : safeSpan === 2 ? 3 : 5
    let gained = 0
    for (let i = 0; i < dropCount; i++) {
      if (!character.hasHandRoom()) break
      // 보물상자 개봉은 일반 드롭 풀에 treasure-only 동전을 추가한다.
      character.addHandCard(DropSystem.generateDrop('treasure'))
      gained++
    }
    HandSystem.runAutoMerges(character)
    return gained
  }

  /** Cards with per-turn behavior can be stopped by wax: active enemies, volatile
   *  treasures, bombs/spores, and bloomed flowers all own a timer-like beat. */
  private static isTurnTimerCard(card: Card): boolean {
    if (card.type === CardType.ENEMY) return true
    if (card.type === CardType.BOSS) return true
    if (card.type === CardType.TREASURE) return true
    if (card.type === CardType.TRAP) return card.trapKind === 'bomb' || card.trapKind === 'spore'
    if (card.type === CardType.FLOWER) return card.flowerKind !== 'seed'
    return false
  }

  /** Apply wax hardening to a selected front card. */
  private static freezeTarget(target: HandTarget | undefined, turns: number): string {
    if (!target) return '굳힐 대상 없음'
    // 보스는 디버프(굳음) 면역이므로 손패 밀랍으로는 상태를 고정하지 않는다.
    if (target.card.type === CardType.BOSS) return `${target.card.name} 저항`
    target.card.freeze(turns)
    return `${target.card.name} ${turns}턴 굳음`
  }

  /** Apply wax hardening to every front card with a turn timer. */
  private static freezeFrontCards(gs: GameState, turns: number): string {
    const seen = new Set<Card>()
    let count = 0
    for (const lane of gs.lanes) {
      const card = lane.getCardAtDistance(0)
      if (!card || seen.has(card)) continue
      if (!HandSystem.isTurnTimerCard(card)) continue
      // 보스는 즉사/디버프 면역 기획: 전방 전체 굳음에도 포함하지 않는다.
      if (card.type === CardType.BOSS) continue
      seen.add(card)
      card.freeze(turns)
      count++
    }
    return `전방 ${count}장 ${turns}턴 굳음`
  }

  /** Remove up to `count` random spore traps; 성수 no longer cleanses other hazards. */
  private static cleanseRandomSpores(gs: GameState, count: number, prefix = ''): string {
    const candidates = HandSystem.collectAllOfType(gs, CardType.TRAP).filter(
      (card) => card.trapKind === 'spore'
    )
    let cleansed = 0
    while (candidates.length > 0 && cleansed < count) {
      const pickIndex = Math.floor(Math.random() * candidates.length)
      const [card] = candidates.splice(pickIndex, 1)
      // removeCardFromRow clears every lane that references the same grouped
      // spore, so a 2/3칸 포자군 still disappears as one selected card.
      for (let d = 0; d < LANE_DISTANCE_COUNT; d++) gs.removeCardFromRow(card, d)
      cleansed++
    }
    return `${prefix}포자 ${cleansed}장 제거`
  }

  /** Triple 성수 removes every spore while preserving webs, bombs, and frozen cards. */
  private static cleanseAllSpores(gs: GameState): string {
    const spores = HandSystem.collectAllOfType(gs, CardType.TRAP).filter(
      (card) => card.trapKind === 'spore'
    )
    for (const card of spores) {
      // Grouped spores share one Card instance, so this clears the whole group.
      for (let d = 0; d < LANE_DISTANCE_COUNT; d++) gs.removeCardFromRow(card, d)
    }
    return `트리플 전체 포자 ${spores.length}장 제거`
  }

  /** Remove the selected front trap. */
  private static removeTargetTrap(gs: GameState, target: HandTarget | undefined): string {
    if (!target || target.card.type !== CardType.TRAP) return '제거할 전방 함정 없음'
    gs.removeCardFromRow(target.card, target.distance)
    return `${target.card.name} 제거`
  }

  /** Find the first matching card anywhere on the 3×3 field. */
  private static findFirstOnField(
    gs: GameState,
    types: CardType[]
  ): { card: Card; laneIndex: number; distance: number } | null {
    for (let laneIndex = 0; laneIndex < gs.lanes.length; laneIndex++) {
      for (let distance = 0; distance < LANE_DISTANCE_COUNT; distance++) {
        const card = gs.lanes[laneIndex].getCardAtDistance(distance)
        if (card && types.includes(card.type)) return { card, laneIndex, distance }
      }
    }
    return null
  }

  private static collectAllOfType(gs: GameState, type: CardType): Card[] {
    const out: Card[] = []
    const seen = new Set<Card>()
    for (const lane of gs.lanes) {
      for (let d = 0; d < LANE_DISTANCE_COUNT; d++) {
        const card = lane.getCardAtDistance(d)
        if (!card || seen.has(card)) continue
        if (card.type === type) {
          seen.add(card)
          out.push(card)
        }
      }
    }
    return out
  }

  private static clearAllOfTypes(gs: GameState, types: CardType[]): number {
    const seen = new Set<Card>()
    let count = 0
    for (const lane of gs.lanes) {
      for (let d = 0; d < LANE_DISTANCE_COUNT; d++) {
        const card = lane.getCardAtDistance(d)
        if (!card || seen.has(card)) continue
        if (types.includes(card.type)) {
          seen.add(card)
          gs.removeCardFromRow(card, d)
          count++
        }
      }
    }
    return count
  }
}
