/**
 * HandSystem - Hand of consumable cards with chain-recipe combos.
 *
 * Core mechanics:
 *   1. Hand stacks bottom-up (slot 0 = bottom). New drops fall to the
 *      lowest empty slot.
 *   2. When three consecutive same-defId cards sit in the stack they
 *      auto-merge into a single enhanced "merged" card at that slot.
 *   3. The player clicks a card to USE it. The card runs its single (or
 *      merged-enhanced) effect and is appended to the active CHAIN.
 *   4. After every use we re-scan the recipe book. Any recipe whose
 *      ingredient multiset is contained in the chain — and that has not
 *      already fired this chain — fires as an additional effect.
 *   5. The chain resets on a board action or on turn end.
 */

import { GameState } from '@core/GameState'
import { Card, CardType, type FlowerKind } from '@entities/Card'
import { Character } from '@entities/Character'
import { LANE_DISTANCE_COUNT } from '@entities/Lane'
import { HandCard, HandCardId, HandCardDefinition, HandEffectTargeting } from '@entities/HandCard'
import { getHandCardDef } from '@data/HandCards'
import { Recipe, RECIPES } from '@data/Recipes'
import { DropSystem } from './DropSystem'

export interface HandTarget {
  laneIndex: number
  distance: number
  card: Card
}

export interface FiredRecipe {
  recipe: Recipe
  /** Short message describing what the recipe did. */
  message: string
  /** Currency generated by recipe effects that pay shop money. */
  coinsGained?: number
  /** defId of a hand card drawn by this specific recipe, if any. */
  drawnHandCardDefId?: HandCardId
}

/** Tracks a single card removed from the board so the UI can play its
 *  consume animation BEFORE the next render erases it. */
export interface RemovedFieldCard {
  cardId: string
  type: CardType
  /** 확산/폭탄 유물용: 제거 직전 카드가 있던 레인(첫 슬롯 기준). 단일 손패 사용 경로에서만 채워진다. */
  laneIndex?: number
  /** 폭탄 유물용: 제거 직전 카드가 있던 거리(행). 단일 손패 사용 경로에서만 채워진다. */
  distance?: number
}

/** 정원 가위로 실제 수확된 꽃 1장 — 체력/방패/게이지는 이미 캐릭터에 반영된 뒤의
 *  통지값이며, 캐모마일(불빛)/금잔화(코인)만 index.ts가 이어서 지급한다. */
export interface FlowerHarvestRecord {
  cardId: string
  name: string
  kind: Exclude<FlowerKind, 'seed'>
  amount: number
}

export interface HandUseResult {
  success: boolean
  /** Single-card effect message. */
  message: string
  /** Cards that auto-merged or were absorbed by a merge after this use. */
  mergeMessages: string[]
  /** Field cards removed by the single hand-card effect only. Recipe removals
   *  are reported by fireNextPendingRecipe after the UI delay. */
  removedFieldCards: RemovedFieldCard[]
  /** Currency gained by a coin hand card; UI applies it to the shop wallet. */
  coinsGained?: number
  /** Extra hand-gauge progress granted by the card's explicit effect. */
  gaugeCountBonus?: number
  /** 탐욕의 동전: 사용자가 즉시 받는 피해. UI가 애니메이션과 함께 적용한다. */
  selfDamage?: number
  /** 탐욕의 동전: 획득 불빛 base값. UI(index.ts)가 인플레이션을 적용해 합산한다. */
  lightGained?: number
  /** 레바테인: index.ts가 피해 적용 전에 runSimulatedEnemyPhase()를 이 횟수만큼 실행한다. */
  simulatedBattlePhases?: number
  /** 레바테인: 시뮬레이션 이후 대상 카드에 입힐 피해량. index.ts가 takeDamage로 적용한다. */
  levateainDamage?: number
  /** 청소(단일): true이면 제거된 필드 카드의 불빛 점수를 부여하지 않는다. */
  suppressScoreForRemovedCards?: boolean
  /** 손거울(트리플): 복제된 손패 ID. index.ts가 획득 로그를 남긴다. */
  mirrorCopiedDefId?: HandCardId
  /** 샹들리에: 처치 발생 시 index.ts가 200ms 딜레이로 동일 라운드를 반복 실행한다.
   *  반복은 한번에 계산하지 않고 처치가 있을 때마다 재실행하는 빠른 연속 실행이다. */
  chandelierRepeat?: { isMerged: boolean }
  /** 주전자: index.ts가 200ms 딜레이로 나머지 타격을 순차 실행한다.
   *  totalCount는 첫 타격 포함 총 횟수 — index.ts는 i=1부터 루프한다.
   *  반복은 한번에 계산하지 않고 매 타격을 독립적으로 실행하는 빠른 연속 타격이다. */
  teapotExtraHits?: { damage: number; totalCount: number }
  /** 모닥불: 처치가 일어났을 때 index.ts가 적용할 체력 회복량. */
  bonfireHealOnKill?: number
  /** 바늘: 자해 딜로 처치가 일어났을 때 index.ts가 적용할 체력 회복량. */
  needleHealOnKill?: number
  /** 검은 양초: 사용 시 악마 보스 피해 카운터를 증가시킬 양. 보스가 없을 때는 무시한다. */
  blackCandleCounterGain?: number
  /** 정원 가위: 실제로 수확된 꽃 목록. index.ts는 이 카드들을 removedFieldCards의
   *  일반 불빛 계산에서 제외하고, 캐모마일/금잔화만 따로 불빛/코인을 지급한다. */
  flowerHarvests?: FlowerHarvestRecord[]
}

export interface RecipeFireResult {
  /** Recipes that fired after the chain-delay beat. */
  firedRecipes: FiredRecipe[]
  /** Field cards removed by those delayed recipe effects. */
  removedFieldCards: RemovedFieldCard[]
  /** Total shop currency generated by fired recipes. */
  coinsGained?: number
  /** Hand-card defIds drawn by recipes such as 셔플 (draw-random-hand-1).
   *  The UI logs each as an item-gain row so any "card drawn" feels
   *  consistent whether the source is a rail drop, the gauge, or a recipe. */
  drawnHandCardDefIds?: HandCardId[]
}

/**
 * The active chain. Lives on the GameState to survive hand re-renders. We
 * track:
 *   - sequence: defIds in the order they were physically used
 *   - firedRecipeIds: recipe ids already triggered for this chain
 */
export interface ChainState {
  sequence: HandCardId[]
  firedRecipeIds: Set<string>
}

interface RecipeEffectResult {
  /** Player-facing effect summary used by the log/banner. */
  message: string
  /** Optional shop money paid by this recipe. */
  coinsGained?: number
  /** defId of a hand card drawn by this recipe, if any. */
  drawnHandCardDefId?: HandCardId
}

export class HandSystem {
  /** 탐욕의 동전 자해 피해는 매 사용마다 2~5 랜덤. */
  static greedCoinSelfDamage(): number { return Math.floor(Math.random() * 4) + 2 }
  /** 탐욕의 동전 불빛 base값(30층 1칸 적 처치의 약 절반). index.ts가 인플레이션을 적용한다. */
  static readonly GREED_COIN_LIGHT_BASE = 36

  /** 정원 가위 수확 기록 임시 버퍼 — applyGardenScissors*가 채우고, useSingle()이
   *  같은 동기 호출 안에서 즉시 비워 HandUseResult.flowerHarvests로 전달한다. */
  private static pendingFlowerHarvests: FlowerHarvestRecord[] = []

  /** ActionSystem.takeFlower와 동일한 종류별 보상을 캐릭터에 직접 반영한다.
   *  캐모마일(불빛)/금잔화(코인)는 캐릭터 상태가 아니므로 여기서 반영할 수 없어
   *  기록만 남기고, index.ts가 flowerHarvests를 읽어 지급한다. */
  private static harvestFlowerReward(character: Character, card: Card): void {
    if (card.type !== CardType.FLOWER || card.flowerKind === 'seed') return
    const amount = Math.max(1, card.flowerValue)
    switch (card.flowerKind) {
      case 'redRose':
        character.heal(amount)
        break
      case 'oleander':
        character.addShield(amount)
        break
      case 'lavender':
        character.gainCandle(amount)
        break
    }
    HandSystem.pendingFlowerHarvests.push({ cardId: card.id, name: card.name, kind: card.flowerKind, amount })
  }

  /** pendingFlowerHarvests를 비우고 반환한다. useSingle()이 정원 가위 사용 직후 1회만 호출한다. */
  private static drainPendingFlowerHarvests(): FlowerHarvestRecord[] {
    const out = HandSystem.pendingFlowerHarvests
    HandSystem.pendingFlowerHarvests = []
    return out
  }

  /** Build a fresh empty chain. */
  static newChain(): ChainState {
    return { sequence: [], firedRecipeIds: new Set() }
  }

  /** Reset the chain in-place (board action / turn end). */
  static resetChain(chain: ChainState): void {
    chain.sequence = []
    chain.firedRecipeIds = new Set()
  }

  /** Insert a freshly drawn drop into the hand at the bottom-most empty slot. */
  static enqueueDrop(character: Character, card: HandCard): boolean {
    const ok = character.addHandCard(card)
    if (ok) HandSystem.runAutoMerges(character)
    return ok
  }

  /** Snapshot every Card present on the field, keyed by id → type. Used to
   *  diff what got removed across an effect application so the UI can play
   *  consume animations on the right cells. */
  private static snapshotFieldCards(gs: GameState): Map<string, CardType> {
    const m = new Map<string, CardType>()
    for (const lane of gs.lanes) {
      for (let d = 0; d < LANE_DISTANCE_COUNT; d++) {
        const c = lane.getCardAtDistance(d)
        if (c) m.set(c.id, c.type)
      }
    }
    return m
  }

  /** 제거 diff에 레인 정보를 함께 담는 상세 스냅샷(확산 유물이 처치 레인을 알아야 한다).
   *  카드가 여러 레인에 걸치면 처음 만난 레인을 기록한다. */
  private static snapshotFieldCardsDetailed(gs: GameState): Map<string, { type: CardType; laneIndex: number; distance: number }> {
    const m = new Map<string, { type: CardType; laneIndex: number; distance: number }>()
    for (let li = 0; li < gs.lanes.length; li++) {
      for (let d = 0; d < LANE_DISTANCE_COUNT; d++) {
        const c = gs.lanes[li].getCardAtDistance(d)
        if (c && !m.has(c.id)) m.set(c.id, { type: c.type, laneIndex: li, distance: d })
      }
    }
    return m
  }

  /** Run a single use on slot `slotIndex`; recipe firing is delayed by index.ts.
   *  `deferAutoMerge`로 트리플 자동 합성을 미루면, UI가 손패 이동/낙하 연출이 끝난 뒤
   *  별도 비트로 합성 연출을 재생할 수 있다(이동·합성 애니메이션 충돌 방지). */
  static useSingle(
    gs: GameState,
    chain: ChainState,
    slotIndex: number,
    target?: HandTarget,
    deferAutoMerge: boolean = false
  ): HandUseResult {
    const character = gs.character
    const card = character.hand[slotIndex]
    if (!card) {
      return { success: false, message: '비어 있는 슬롯', mergeMessages: [], removedFieldCards: [] }
    }
    const def = getHandCardDef(card.defId)
    if (!HandSystem.isValidTarget(def, target, card.merged === true)) {
      return {
        success: false,
        message: `${def.name}은(는) 조건에 맞는 대상을 골라야 해`,
        mergeMessages: [],
        removedFieldCards: [],
      }
    }

    // Snapshot the field BEFORE any mutation so we can diff removals after.
    // 상세 스냅샷으로 제거 카드의 레인까지 담아 확산 유물이 처치 레인을 알 수 있게 한다.
    const beforeField = HandSystem.snapshotFieldCardsDetailed(gs)

    // 주전자: 효과 실행 전에 필드 적 수를 캡처해 총 타격 횟수를 결정한다(효과 후 적 수가 변할 수 있음).
    const preEffectEnemyCount = card.defId === 'teapot' ? HandSystem.countFieldEnemies(gs) : 0

    // Apply the card effect (merged cards use the enhanced version).
    const message = card.merged
      ? HandSystem.applyTripleEffect(gs, def, target)
      : HandSystem.applySingleEffect(gs, def, target)

    character.removeHandCardAt(slotIndex)

    // 검은 양초: 사용 후 즉시 손패로 복귀한다 — 소모되지 않는 카드.
    if (card.defId === 'black-candle') {
      character.addHandCard(DropSystem.makeCard('black-candle'))
    }

    // Extend the visible recipe chain with exactly one real card entry. The
    // `카드` item's combo-count text now means hand-gauge progress, not hidden
    // recipe ingredients, so recipes still read only this physical sequence.
    // 손거울 트리플: chain에 현재 카드가 추가되기 전에 이전 손패를 복제한다.
    let mirrorCopiedDefId: HandCardId | undefined
    if (card.defId === 'hand-mirror' && card.merged === true && chain.sequence.length > 0) {
      const lastDefId = chain.sequence[chain.sequence.length - 1]
      if (character.hasHandRoom()) {
        character.addHandCard(DropSystem.makeCard(lastDefId))
        mirrorCopiedDefId = lastDefId
      }
    }

    chain.sequence.push(card.defId)
    const baseGaugeBonus = HandSystem.gaugeCountBonusFor(card.defId, card.merged === true)
    const extraGaugeBonus = card.defId === 'card'
      ? (card.merged
          ? (gs.enhancements.tripleBonus['card'] ?? 0)
          : (gs.enhancements.singleBonus['card'] ?? 0))
      : 0
    const gaugeCountBonus = baseGaugeBonus + extraGaugeBonus
    if (gaugeCountBonus > 0) character.gainCandle(gaugeCountBonus)

    // Recipes are deliberately resolved later by fireNextPendingRecipe(), which
    // gives the UI a readable beat between the card effect and combo explosion.
    // deferAutoMerge면 합성을 미뤄 두고, index.ts가 손패 이동 연출 뒤 runAutoMerges를 직접 호출한다.
    const mergeMessages = deferAutoMerge ? [] : HandSystem.runAutoMerges(character)

    // 카드를 쓰면 콤보 게이지가 오른다. 3장이 합쳐진 트리플 카드는 3장을 한 번에 쓴
    // 셈이므로 +3, 일반 카드는 +1. 탐욕의 동전은 게이지를 올리지 않는다.
    if (card.defId !== 'greed-coin') character.gainCandle(card.merged ? 3 : 1)

    // Diff the field snapshot to record removed cards for animation.
    const afterField = HandSystem.snapshotFieldCards(gs)
    const removedFieldCards: RemovedFieldCard[] = []
    for (const [id, info] of beforeField.entries()) {
      if (!afterField.has(id)) removedFieldCards.push({ cardId: id, type: info.type, laneIndex: info.laneIndex, distance: info.distance })
    }

    return {
      success: true,
      message,
      mergeMessages,
      removedFieldCards,
      coinsGained: card.defId === 'coin'
        ? (card.merged
            ? 5 + (gs.enhancements.tripleBonus['coin'] ?? 0)
            : 1 + (gs.enhancements.singleBonus['coin'] ?? 0))
        : 0,
      gaugeCountBonus,
      // 자해 피해와 불빛은 UI가 애니메이션과 함께 적용한다(모델은 여기서 건드리지 않음).
      selfDamage: HandSystem.selfDamageFor(card.defId, card.merged === true),
      lightGained: card.defId === 'greed-coin' ? HandSystem.GREED_COIN_LIGHT_BASE : 0,
      // 레바테인/족쇄: 시뮬레이션 페이즈 수를 index.ts에 전달해 적 행동을 먼저 실행하게 한다.
      simulatedBattlePhases: card.defId === 'levatein' ? (card.merged ? 1 : 2)
        : card.defId === 'shackles' ? 1
        : undefined,
      // 레바테인 피해: floor(배율 × 최대체력) + 기본값. Max 대신 addend 방식.
      levateainDamage: card.defId === 'levatein'
        ? (card.merged
          ? Math.floor((target?.card.enemyHealthTotal ?? 0) * 0.45) + 15
          : Math.floor((target?.card.enemyHealthTotal ?? 0) * 0.30) + 10)
        : undefined,
      // 청소 단일: 제거된 거미줄의 불빛을 주지 않는다(트리플만 불빛 획득).
      suppressScoreForRemovedCards: card.defId === 'sweep' && !card.merged,
      mirrorCopiedDefId,
      chandelierRepeat: card.defId === 'chandelier' ? { isMerged: card.merged === true } : undefined,
      // 주전자: 첫 타격 포함 총 타격 횟수와 타격 피해를 index.ts에 전달한다.
      // 주전자: 단일 floor(1.5×공) × 적수, 트리플 floor(3.0×공) × 적수×3.
      teapotExtraHits: card.defId === 'teapot' && preEffectEnemyCount > 0
        ? {
            damage: card.merged
              ? Math.floor(3 * gs.character.damage) + (gs.enhancements.tripleBonus['teapot'] ?? 0)
              : Math.floor(1.5 * gs.character.damage) + (gs.enhancements.singleBonus['teapot'] ?? 0),
            totalCount: card.merged ? preEffectEnemyCount * 3 : preEffectEnemyCount,
          }
        : undefined,
      bonfireHealOnKill: card.defId === 'bonfire'
        ? (card.merged
            ? 5 + (gs.enhancements.tripleBonus['bonfire'] ?? 0)
            : 3 + (gs.enhancements.singleBonus['bonfire'] ?? 0))
        : undefined,
      // 바늘: 자해 딜로 처치가 나면 단일 +3 / 트리플 +5 회복(index.ts가 removedFieldCards로 판정).
      needleHealOnKill: card.defId === 'needle'
        ? (card.merged
            ? 5 + (gs.enhancements.tripleBonus['needle'] ?? 0)
            : 3 + (gs.enhancements.singleBonus['needle'] ?? 0))
        : undefined,
      // 검은 양초: 사용 시 악마 보스 카운터 증가량을 전달 (단일+2, 트리플+6).
      blackCandleCounterGain: card.defId === 'black-candle'
        ? (card.merged ? 6 : 2)
        : undefined,
      // 정원 가위: 실제 수확된 꽃 기록 — 캐모마일/금잔화 불빛·코인 지급은 index.ts가 이어받는다.
      flowerHarvests: card.defId === 'garden-scissors' ? HandSystem.drainPendingFlowerHarvests() : undefined,
    }
  }

  /** 카드별 자해 피해(UI가 애니메이션과 함께 적용). 탐욕의 동전·제물 양초·희생 방패가 사용한다. */
  private static selfDamageFor(defId: HandCardId, isMerged: boolean): number {
    if (defId === 'greed-coin') return HandSystem.greedCoinSelfDamage()
    // 제물 양초: 단일 자해 2, 트리플 자해 5.
    if (defId === 'sacrifice-candle') return isMerged ? 5 : 2
    // 의식 양초: 단일 자해 2, 트리플 자해 1.
    if (defId === 'ritual-candle') return isMerged ? 1 : 2
    // 희생 방패: 단일 자해 1, 트리플 자해 2.
    if (defId === 'sacrifice-shield') return isMerged ? 2 : 1
    // 바늘: 단일 자해 1, 트리플 자해 2.
    if (defId === 'needle') return isMerged ? 2 : 1
    // 부두 인형: 단일/트리플 모두 자해 2.
    if (defId === 'voodoo-doll') return 2
    // 단두대: 단일 자해 6, 트리플 자해 10(대량 자해 펌프).
    if (defId === 'guillotine') return isMerged ? 10 : 6
    // 검은 양초: 단일 자해 2, 트리플 자해 4.
    if (defId === 'black-candle') return isMerged ? 4 : 2
    return 0
  }

  /** Extra hand-gauge progress contributed by cards with combo-count effects. */
  private static gaugeCountBonusFor(defId: HandCardId, isMerged: boolean): number {
    if (defId !== 'card') return 0
    return isMerged ? 7 : 1
  }

  /** Recipe ingredient count of `id`; only physically played cards qualify. */
  private static countInChain(chain: ChainState, id: HandCardId): number {
    let n = 0
    for (const d of chain.sequence) if (d === id) n++
    return n
  }

  /** Recipe is contained in chain when each ingredient count is satisfied. */
  private static recipeMatches(recipe: Recipe, chain: ChainState): boolean {
    for (const [id, needed] of Object.entries(recipe.ingredients)) {
      if (!needed) continue
      if (HandSystem.countInChain(chain, id as HandCardId) < needed) return false
    }
    return true
  }

  /** runLocked 레시피를 런 해금 여부에 따라 필터한다. gs 없으면 전체 반환(도감 등 비전투 용도). */
  private static activeRecipes(gs?: GameState): Recipe[] {
    if (!gs) return RECIPES
    return RECIPES.filter((r) => !r.runLocked || gs.unlockedRecipeIds.has(r.id))
  }

  /**
   * Return every not-yet-fired recipe that would become active if `defId` were
   * used now. The renderer consumes this as a non-mutating hint source so recipe
   * glow rules stay tied to the same declarative recipe book as real gameplay.
   */
  static previewTriggeredRecipes(
    chain: ChainState,
    defId: HandCardId,
    _isMerged: boolean = false,
    gs?: GameState
  ): Recipe[] {
    const preview: ChainState = {
      sequence: [...chain.sequence, defId],
      firedRecipeIds: new Set(chain.firedRecipeIds),
    }
    // Recipe hints intentionally mirror physical ingredient rules, not gauge
    // progress: one `카드` preview must not promise `셔플`.
    // Guard: only highlight when THIS card is what completes the recipe.
    // Without this, a recipe satisfied by chain.sequence (but not yet fired)
    // would light up every card in hand until firedRecipeIds catches up.
    return HandSystem.activeRecipes(gs).filter((recipe) => {
      if (preview.firedRecipeIds.has(recipe.id)) return false
      if (HandSystem.recipeMatches(recipe, chain)) return false
      return HandSystem.recipeMatches(recipe, preview)
    })
  }

  /** Check whether the current chain has at least one newly satisfied recipe. */
  static hasPendingRecipe(chain: ChainState, gs?: GameState): boolean {
    for (const recipe of HandSystem.activeRecipes(gs)) {
      if (chain.firedRecipeIds.has(recipe.id)) continue
      if (HandSystem.recipeMatches(recipe, chain)) return true
    }
    return false
  }

  /** Fire exactly one pending recipe so the UI can compact/refill between combo beats. */
  static fireNextPendingRecipe(gs: GameState, chain: ChainState): RecipeFireResult {
    const beforeField = HandSystem.snapshotFieldCards(gs)
    const firedRecipe = HandSystem.fireNextMatchedRecipe(gs, chain)
    const afterField = HandSystem.snapshotFieldCards(gs)
    const removedFieldCards: RemovedFieldCard[] = []
    for (const [id, type] of beforeField.entries()) {
      if (!afterField.has(id)) removedFieldCards.push({ cardId: id, type })
    }
    const firedRecipes = firedRecipe ? [firedRecipe] : []
    const drawnHandCardDefIds = firedRecipe?.drawnHandCardDefId
      ? [firedRecipe.drawnHandCardDefId]
      : undefined
    return {
      firedRecipes,
      removedFieldCards,
      coinsGained: firedRecipe?.coinsGained ?? 0,
      drawnHandCardDefIds,
    }
  }

  private static fireNextMatchedRecipe(gs: GameState, chain: ChainState): FiredRecipe | null {
    // Sort by ingredient size ascending so smaller recipes resolve first.
    const sorted = [...HandSystem.activeRecipes(gs)].sort((a, b) => a.totalCount - b.totalCount)
    for (const recipe of sorted) {
      if (chain.firedRecipeIds.has(recipe.id)) continue
      if (!HandSystem.recipeMatches(recipe, chain)) continue
      const effect = HandSystem.applyRecipeEffect(gs, recipe)
      chain.firedRecipeIds.add(recipe.id)
      return {
        recipe,
        message: effect.message,
        coinsGained: effect.coinsGained,
        drawnHandCardDefId: effect.drawnHandCardDefId,
      }
    }
    return null
  }

  /** Apply a recipe's effect against the GameState. */
  private static applyRecipeEffect(gs: GameState, recipe: Recipe): RecipeEffectResult {
    const c = gs.character
    const rb = gs.enhancements.recipeBonus
    const bonus = rb[recipe.id] ?? 0

    // 보스 전투 중에는 필드 카드를 변형·수집하는 레시피가 일반 레일에 영향을 주면 안 된다.
    // 피해를 주는 레시피(damage-*)는 보스에게도 반영하므로 차단하지 않는다.
    const BOSS_BLOCKED_EFFECTS: ReadonlySet<Recipe['effect']> = new Set([
      'collect-random-treasure',
      'convert-random-waiting-to-treasure',
      'convert-random-hazard-to-treasure',
      'clear-all-field-cards',
      'collect-waiting-treasures',
    ])
    if (gs.bossBattleActive && BOSS_BLOCKED_EFFECTS.has(recipe.effect)) {
      return { message: '보스 전투 중 — 필드 효과 차단' }
    }

    switch (recipe.effect) {
      case 'gain-wax-drop': {
        if (!c.hasHandRoom()) return { message: '손패가 가득 차 촛농 획득 실패' }
        c.addHandCard(DropSystem.makeCard('wax-drop'))
        HandSystem.runAutoMerges(c)
        return { message: '촛농 1장 획득', drawnHandCardDefId: 'wax-drop' }
      }
      case 'damage-all-field-enemies-1':
        return { message: HandSystem.damageEnemies(gs, 'field', 1 + bonus) }
      case 'gain-coin-1': {
        const total = 1 + bonus
        return { message: `+${total}$`, coinsGained: total }
      }
      case 'draw-random-hand-1': {
        // 셔플 강화: bonus장 추가 드로우
        const count = 1 + bonus
        let lastId: HandCardId | undefined
        for (let i = 0; i < count; i++) {
          if (!c.hasHandRoom()) break
          const drop = DropSystem.generateDrop()
          c.addHandCard(drop)
          lastId = drop.defId
        }
        HandSystem.runAutoMerges(c)
        return lastId
          ? { message: `랜덤 손패 ${count}장 획득`, drawnHandCardDefId: lastId }
          : { message: '손패가 가득 차 드로우 실패' }
      }
      case 'destroy-random-front-enemy': {
        // 양초 스매쉬 강화: 1+bonus장 처치
        const msgs: string[] = []
        for (let i = 0; i < 1 + bonus; i++) msgs.push(HandSystem.destroyRandomFrontEnemy(gs))
        return { message: msgs.join(' / ') }
      }
      case 'convert-random-hazard-to-treasure': {
        // 지뢰제거반 강화: bonus회 추가 변환
        const msgs: string[] = []
        for (let i = 0; i < 1 + bonus; i++) msgs.push(HandSystem.convertRandomHazardToTreasure(gs))
        return { message: msgs.join(' / ') }
      }
      case 'collect-random-treasure': {
        // 열쇠공 강화: bonus개 추가 획득
        const msgs: string[] = []
        for (let i = 0; i < 1 + bonus; i++) msgs.push(HandSystem.collectRandomTreasure(gs, c))
        return { message: msgs.join(' / ') }
      }
      case 'convert-random-waiting-to-treasure': {
        // 탐욕 강화: bonus칸 추가 변환
        const msgs: string[] = []
        for (let i = 0; i < 1 + bonus; i++) msgs.push(HandSystem.convertRandomWaitingSlotToTreasure(gs))
        return { message: msgs.join(' / ') }
      }
      case 'clear-all-field-cards': {
        // "필드의 모든 칸 제거" — 꽃 칸도 포함해 전부 제거한다(보스만 타입 미포함으로 면역).
        const cleared = HandSystem.clearAllOfTypes(gs, [
          CardType.ENEMY,
          CardType.TRAP,
          CardType.TREASURE,
          CardType.FLOWER,
        ])
        return { message: `필드 ${cleared}장 제거` }
      }
      case 'damage-front-enemies-3':
        return { message: HandSystem.damageEnemies(gs, 'front', 3 + bonus) }
      case 'clear-front-cards':
        return { message: HandSystem.clearFrontCards(gs) }
      case 'collect-waiting-treasures':
        return { message: HandSystem.collectWaitingTreasures(gs, c) }
      case 'damage-front-enemies-2':
        return { message: HandSystem.damageEnemies(gs, 'front', 2 + bonus) }
      case 'damage-all-field-enemies-2':
        return { message: HandSystem.damageEnemies(gs, 'field', 2 + bonus) }
      case 'damage-front-enemies-5':
        return { message: HandSystem.damageEnemies(gs, 'front', 5 + bonus) }
      case 'damage-all-field-enemies-5':
        return { message: HandSystem.damageEnemies(gs, 'field', 5 + bonus) }
      case 'gain-ember-3': {
        const gained = c.gainEmber(3 + bonus)
        return { message: `빛 게이지 +${gained}` }
      }
      case 'heal-5': {
        const healed = c.heal(5 + bonus)
        return { message: `체력 +${healed}` }
      }
      case 'heal-3': {
        const healed = c.heal(3 + bonus)
        return { message: `체력 +${healed}` }
      }
      case 'damage-split-field-4':
        return { message: HandSystem.distributeDamageAmongEnemies(gs, 4 + bonus) }
      case 'clear-all-field-traps': {
        const cleared = HandSystem.clearAllOfTypes(gs, [CardType.TRAP])
        return { message: `필드 함정 ${cleared}장 제거` }
      }
      case 'damage-split-field-5':
        return { message: HandSystem.distributeDamageAmongEnemies(gs, 5 + bonus) }
      case 'destroy-all-front-enemies': {
        // 끓는 분노: 전방 모든 적을 처치한다(보스 면역).
        const killed = HandSystem.destroyAllFrontEnemies(gs)
        return { message: `전방 적 ${killed}체 처치` }
      }
      case 'gain-ember-2': {
        const gained = c.gainEmber(2 + bonus)
        return { message: `빛 게이지 +${gained}` }
      }
      case 'shield-2-and-damage-field-1': {
        // 불꽃 사슬: 방패 고정 +2, 피해에만 bonus 적용.
        c.addShield(2)
        return { message: HandSystem.damageEnemies(gs, 'field', 1 + bonus) }
      }
      case 'damage-split-field-2x2': {
        // 연회: 피해 2 분산을 2회 순차 실행한다(한번에 4로 계산하지 않음).
        HandSystem.distributeDamageAmongEnemies(gs, 2 + bonus)
        return { message: HandSystem.distributeDamageAmongEnemies(gs, 2 + bonus) }
      }
      case 'heal-by-player-attack': {
        const amount = c.damage + bonus
        const healed = c.heal(amount)
        return { message: `공격력(${amount})만큼 체력 +${healed}` }
      }
      // ATK 연동 레시피 효과 ─ 공격력 기반 스케일링
      case 'ignite-atk':
        return { message: HandSystem.damageEnemies(gs, 'field', Math.floor(0.3 * c.damage) + 1 + bonus) }
      case 'hot-atk':
        return { message: HandSystem.damageEnemies(gs, 'front', Math.floor(0.5 * c.damage) + 2 + bonus) }
      case 'fuse-atk':
        return { message: HandSystem.damageEnemies(gs, 'front', Math.floor(1.5 * c.damage) + bonus) }
      case 'backfire-atk':
        return { message: HandSystem.damageEnemies(gs, 'field', Math.floor(c.damage) + bonus) }
      case 'rage-atk':
        return { message: HandSystem.damageEnemies(gs, 'front', Math.floor(c.damage) + 3 + bonus) }
      case 'flame-chain-atk': {
        c.addShield(2)
        return { message: HandSystem.damageEnemies(gs, 'field', Math.floor(c.damage) + bonus) }
      }
      case 'glass-shards-atk':
        return { message: HandSystem.distributeDamageAmongEnemies(gs, Math.floor(0.5 * c.damage) + 3 + bonus) }
      case 'fireworks-atk':
        return { message: HandSystem.distributeDamageAmongEnemies(gs, Math.floor(3 * c.damage) + 3 + bonus) }
      case 'banquet-atk': {
        // floor(1.0×공) 피해를 공격력 횟수만큼 반복 분산
        const dmgPerHit = Math.floor(c.damage) + bonus
        const times = Math.max(1, c.damage)
        for (let i = 0; i < times - 1; i++) HandSystem.distributeDamageAmongEnemies(gs, dmgPerHit)
        return { message: HandSystem.distributeDamageAmongEnemies(gs, dmgPerHit) }
      }
      case 'hot-water-maxhp': {
        // 전방 랜덤 적 1장에게 최대체력 × 0.2 피해
        const frontEnemies: HandTarget[] = []
        const seenCards = new Set<Card>()
        for (let laneIdx = 0; laneIdx < gs.lanes.length; laneIdx++) {
          const card = gs.lanes[laneIdx].getCardAtDistance(0)
          if (!card || seenCards.has(card)) continue
          if (card.type !== CardType.ENEMY && card.type !== CardType.BOSS) continue
          seenCards.add(card)
          frontEnemies.push({ card, distance: 0, laneIndex: laneIdx })
        }
        if (frontEnemies.length === 0) return { message: '전방 적 없음' }
        const pick = frontEnemies[Math.floor(Math.random() * frontEnemies.length)]
        const amount = Math.floor((pick.card.enemyHealthTotal ?? pick.card.getHealth()) * 0.2) + bonus
        return { message: HandSystem.damageTargetEnemy(gs, pick, amount) }
      }
    }
  }

  /** 불씨 공격 손패의 피해 보너스(뜨거운 돌 + 기름병). flame 태그 + damageProfile(공격 카드)로
   *  판정하므로 미래 불씨 공격 손패도 자동 적용된다(match처럼 damageProfile 없는 도구는 제외).
   *  표준 `+bonus` 피해식에 folding된다.
   *  - 뜨거운 돌: 밝음(빛 게이지 ≥7)일 때 +(floor(0.25공)+1).
   *  - 기름병: 이번 턴 앞서 쓴 불씨 손패 수만큼 +N(연속 사용 배율, 턴 갱신 시 초기화). */
  static flameDamageBonus(gs: GameState, def: HandCardDefinition): number {
    const c = gs.character
    if (!def.damageProfile || !def.synergyTags?.includes('flame')) return 0
    let bonus = 0
    // '밝음' 티어 하한은 절대 ember 7(기획 고정 규칙). emberMax와 무관.
    if (c.hasRelic('hot-stone') && c.ember >= 7) bonus += Math.floor(0.25 * c.damage) + 1
    if (c.hasRelic('oil-bottle')) bonus += gs.enhancements.oilBottleTurnUses
    return bonus
  }

  /** 방화광용: 필드 전체 적/보스에게 amount 피해. 제거된 적 카드 목록을 돌려줘 호출부가 애니메이션한다. */
  static damageAllEnemies(gs: GameState, amount: number): { cardId: string; defeated: boolean }[] {
    const hits: { cardId: string; defeated: boolean }[] = []
    const seen = new Set<Card>()
    for (let lane = 0; lane < gs.lanes.length; lane++) {
      for (let d = 0; d < LANE_DISTANCE_COUNT; d++) {
        const card = gs.lanes[lane].getCardAtDistance(d)
        if (!card || seen.has(card)) continue
        if (card.type !== CardType.ENEMY && card.type !== CardType.BOSS) continue
        seen.add(card)
        card.takeDamage(amount)
        const defeated = card.getHealth() <= 0
        if (defeated && card.type !== CardType.BOSS) gs.removeCardFromRow(card, d)
        hits.push({ cardId: card.id, defeated })
      }
    }
    return hits
  }

  /** Apply a hand card's single-use effect. coin/card 보너스는 use()에서 처리한다. */
  private static applySingleEffect(
    gs: GameState,
    def: HandCardDefinition,
    target?: HandTarget
  ): string {
    const c = gs.character
    const bonus = (gs.enhancements.singleBonus[def.id] ?? 0) + HandSystem.flameDamageBonus(gs, def)
    switch (def.id) {
      case 'wax-drop': {
        const healed = c.heal(1 + bonus)
        return `체력 +${healed}`
      }
      case 'candle': {
        const shielded = c.addShield(1 + bonus)
        return `방패 +${shielded}`
      }
      case 'ember':
        // 피해 = 1.0 × 공격력 + 1 (강화 보너스 별도 합산)
        return HandSystem.damageTargetEnemy(gs, target, c.damage + 1 + bonus)
      case 'key':
        return HandSystem.collectRandomTreasure(gs, c)
      case 'wax':
        return HandSystem.freezeTarget(target, 1)
      case 'match': {
        const gained = c.gainEmber(1 + bonus)
        return `빛 게이지 +${gained}`
      }
      case 'holy-water':
        return HandSystem.cleanseRandomSpores(gs, 2)
      case 'chitin':
        return HandSystem.removeTargetTrap(gs, target)
      case 'card':
        // gainCandle 보너스는 use()에서 gs.enhancements.singleBonus['card']로 처리.
        return `콤보 게이지 +${1 + bonus}`
      case 'coin':
        // coinsGained 보너스는 use()에서 처리.
        return `+${1 + bonus}$`
      case 'greed-coin':
        // 자해 피해/불빛은 use()의 selfDamage·lightGained로 보고되어 UI에서 처리한다.
        return '소량의 불빛 · 자해 2~5'
      case 'sacrifice-candle':
        // 자해 2는 use()의 selfDamage로 처리. 여기서는 선택 적 피해만 적용한다.
        return HandSystem.damageTargetEnemy(gs, target, Math.floor(1.5 * c.damage) + 3 + bonus)
      case 'levatein':
        // 적 행동 시뮬레이션(2회)과 ♥피해는 levateainDamage로 index.ts에 위임한다.
        return '레바테인: 즉시 2턴 흐름 후 (0.3♥+10)피해'
      case 'firework':
        return HandSystem.distributeDamageAmongEnemies(gs, Math.floor(c.damage) + 2 + bonus)
      case 'book-of-flames':
        return HandSystem.applyBookOfFlames(gs, target, c.damage, 1)
      case 'fire-arrow': {
        // 1 ~ floor(1.0×공)+3 범위 무작위 피해
        const max = Math.max(1, Math.floor(c.damage) + 3 + bonus)
        const damage = Math.ceil(Math.random() * max)
        return HandSystem.damageTargetEnemy(gs, target, damage)
      }
      case 'shield-bash': {
        const damage = Math.max(0, c.shield) + bonus
        return HandSystem.damageTargetEnemy(gs, target, damage)
      }
      case 'blade-shard':
        // 랜덤 적 1체에게 (1+연마) 풀피해 한 방(관통/도탄/폭풍 유물 반영).
        HandSystem.throwBladeShardHit(gs, 1 + bonus)
        return '칼날 파편 투척'
      case 'blade-tome': {
        // 통산 파편 사용 수에 비례해(5회당 +1발) 파편을 여러 발 투척. 각 발은 파편과 같은 규칙.
        const throws = 1 + Math.floor((gs.enhancements.bladeShardUseCount ?? 0) / 5)
        const dmg = 1 + (gs.enhancements.singleBonus['blade-shard'] ?? 0)
        for (let i = 0; i < throws; i++) HandSystem.throwBladeShardHit(gs, dmg)
        return `칼날 파편 ${throws}발 투척`
      }
      case 'scabbard': {
        // 칼날 파편 1~2장(+강화)을 손에 생성한다. 손패가 가득 차면 거기까지만.
        const count = 1 + Math.floor(Math.random() * 2) + bonus
        let made = 0
        for (let i = 0; i < count; i++) {
          if (!c.hasHandRoom()) break
          c.addHandCard(DropSystem.makeCard('blade-shard'))
          made++
        }
        return made > 0 ? `칼날 파편 +${made}` : '손패 가득 참'
      }
      case 'sacrifice-shield': {
        // 자해는 selfDamageFor에서 처리. 방패 획득만 여기서 적용.
        const shielded = c.addShield(2 + bonus)
        return `자해 1 · 방패 +${shielded}`
      }
      case 'sweep':
        return HandSystem.clearSingleCellWebTraps(gs)
      case 'hand-mirror':
        return HandSystem.damageTargetEnemyByAtk(gs, target, bonus)
      case 'chandelier':
        // 처치 발생 시 index.ts가 200ms 딜레이로 동일 라운드를 반복 실행한다(chandelierRepeat 참조).
        return HandSystem.damageEnemies(gs, 'field', Math.floor(0.5 * c.damage) + 1 + bonus)
      case 'bonfire':
        // 처치 발생 시 회복은 index.ts가 bonfireHealOnKill로 처리한다.
        return HandSystem.damageTargetEnemy(gs, target, Math.floor(c.damage) + bonus)
      case 'teapot':
        // 첫 타격만 여기서 실행. 나머지는 index.ts가 200ms 딜레이로 순차 실행한다(teapotExtraHits 참조).
        return HandSystem.damageTargetEnemy(gs, target, Math.floor(1.5 * c.damage) + bonus)
      case 'teacup': {
        const count = HandSystem.countFieldEnemies(gs)
        const healed = c.heal(count + bonus)
        return `체력 +${healed}`
      }
      case 'top-hat': {
        if (!target) return '이동할 카드 없음'
        HandSystem.rotateFrontToBack(gs, target.laneIndex)
        return `${target.card.name} 레인 맨 뒤로 이동`
      }
      case 'slash':
        return HandSystem.damageTargetEnemy(gs, target, Math.floor(2 * c.damage) + 2 + bonus)
      case 'shackles': {
        // 즉시 1턴 흐름은 simulatedBattlePhases=1로 index.ts에 위임한다.
        const shielded = c.addShield(4 + bonus)
        return `방패 +${shielded}`
      }
      case 'candle-tome': {
        const enemyCount = HandSystem.countFieldEnemies(gs)
        const shielded = c.addShield(enemyCount + bonus)
        return `필드 적 ${enemyCount}마리 → 방패 +${shielded}`
      }
      case 'sword-and-shield': {
        const dmg = HandSystem.damageTargetEnemy(gs, target, Math.floor(0.5 * c.damage) + 1 + bonus)
        const shielded = c.addShield(1 + bonus)
        return `${dmg} · 방패 +${shielded}`
      }
      case 'watering-can': {
        if (!target || target.card.type !== CardType.FLOWER) return '꽃 대상 없음'
        const grew = target.card.growFlowerValueOnly(1 + bonus)
        return grew ? `${target.card.name} 성장 → 수확값 +${1 + bonus}` : '씨앗은 성장 불가'
      }
      case 'garden-scissors':
        return HandSystem.applyGardenScissorsSingle(gs, target)
      case 'ritual-candle': {
        // 자해 2는 selfDamageFor에서 처리. 랜덤 손패 드로우만 여기서 실행.
        const count = 1 + bonus
        let gained = 0
        for (let i = 0; i < count; i++) {
          if (!c.hasHandRoom()) break
          c.addHandCard(DropSystem.generateDrop())
          gained++
        }
        return gained > 0 ? `자해 2 · 랜덤 손패 +${gained}` : '자해 2 · 손패 가득 참'
      }
      case 'black-candle':
        // 자해 2는 selfDamageFor, 카운터 +2는 HandUseResult.blackCandleCounterGain으로 처리.
        // 복귀(return-to-hand)는 use()에서 처리. 피해는 book-of-flames와 동일하게 누적.
        return HandSystem.applyBlackCandle(gs, target, 2, 2)
      case 'needle':
        // 자해 1은 selfDamageFor, 처치 회복은 needleHealOnKill로 처리. 무작위 단일 피해만 적용.
        return HandSystem.damageRandomFieldEnemy(gs, Math.floor(0.5 * c.damage) + 1 + bonus)
      case 'voodoo-doll':
        // 자해 2는 selfDamageFor. 선택 1칸이 보물이면 수확, 함정이면 제거.
        return HandSystem.applyVoodooDoll(gs, c, target)
      case 'guillotine':
        // 자해 6은 selfDamageFor. 필드 전체 적에게 (1.0공+3) 확정 피해.
        return HandSystem.damageEnemies(gs, 'field', Math.floor(c.damage) + 3 + bonus)
    }
  }

  /** Apply the enhanced merged-card effect. coin/card 보너스는 use()에서 별도 처리한다. */
  private static applyTripleEffect(
    gs: GameState,
    def: HandCardDefinition,
    target?: HandTarget
  ): string {
    const c = gs.character
    const bonus = (gs.enhancements.tripleBonus[def.id] ?? 0) + HandSystem.flameDamageBonus(gs, def)
    switch (def.id) {
      case 'wax-drop': {
        const healed = c.heal(5 + bonus)
        return `트리플 체력 +${healed}`
      }
      case 'candle': {
        const shielded = c.addShield(5 + bonus)
        return `트리플 방패 +${shielded}`
      }
      case 'ember':
        // 피해 = 3.0 × 공격력 + 5 (트리플 비례 스케일링)
        return HandSystem.damageTargetEnemy(gs, target, 3 * c.damage + 5 + bonus)
      case 'key':
        return HandSystem.collectAllTreasures(gs, c)
      case 'wax':
        return HandSystem.freezeFrontCards(gs, 3 + bonus)
      case 'match': {
        const gained = c.gainEmber(5 + bonus)
        return `트리플 빛 게이지 +${gained}`
      }
      case 'holy-water':
        return HandSystem.cleanseAllSpores(gs)
      case 'chitin': {
        // 트리플도 단일 대상이되 3칸 함정까지 제거 가능(폭 제한은 targeting.maxSpan).
        return HandSystem.removeTargetTrap(gs, target)
      }
      case 'card': {
        // gainCandle 호출은 use()에서 gs.enhancements를 직접 읽어 처리한다.
        const total = 7 + bonus
        return `트리플 콤보 게이지 +${total}`
      }
      case 'coin':
        // coinsGained는 use()에서 처리된다.
        return `+${5 + bonus}$`
      case 'greed-coin':
        // 탐욕의 동전은 트리플 합성되지 않으므로 이 분기는 실제로 도달하지 않는다.
        return '소량의 불빛 · 자해 2~5'
      case 'sacrifice-candle':
        // 자해 5는 selfDamageFor에서 처리. 여기서는 피해만 적용한다.
        return HandSystem.damageTargetEnemy(gs, target, Math.floor(5 * c.damage) + 10 + bonus)
      case 'levatein':
        // 적 행동 시뮬레이션(1회)과 ♥피해는 levateainDamage로 index.ts에 위임한다.
        return '레바테인: 즉시 1턴 흐름 후 (0.45♥+15)피해'
      case 'firework':
        return HandSystem.distributeDamageAmongEnemies(gs, Math.floor(3 * c.damage) + 10 + bonus)
      case 'book-of-flames':
        // 단일 공식의 2배 피해 + 스택 2배 속도(+2/사용). bonus(강화팩) 미반영 — book-of-flames는 고유 누적만 사용.
        return HandSystem.applyBookOfFlames(gs, target, c.damage, 2, 2)
      case 'fire-arrow': {
        // 5 ~ floor(3.0×공) 범위 무작위 피해
        const maxDmg = Math.max(5, Math.floor(3 * c.damage) + bonus)
        const damage = 5 + Math.floor(Math.random() * Math.max(1, maxDmg - 4))
        return HandSystem.damageTargetEnemy(gs, target, damage)
      }
      case 'shield-bash': {
        // 방패를 먼저 얻어 수치를 올린 뒤 배율(3+bonus)배를 피해로 전환한다.
        c.addShield(3)
        const damage = Math.max(0, c.shield) * (3 + bonus)
        return `방패 +3 · ${HandSystem.damageTargetEnemy(gs, target, damage)}`
      }
      case 'blade-shard':
        // 트리플: 3발로 쪼개지 않고 한 적에게 (3+연마) 강타 한 방(단일). 넘침이 커 도탄과 궁합.
        HandSystem.throwBladeShardHit(gs, 3 + bonus)
        return '칼날 파편 강타'
      case 'blade-tome': {
        // 트리플: 투척 발수 2배.
        const throws = (1 + Math.floor((gs.enhancements.bladeShardUseCount ?? 0) / 5)) * 2
        const dmg = 1 + (gs.enhancements.tripleBonus['blade-shard'] ?? 0)
        for (let i = 0; i < throws; i++) HandSystem.throwBladeShardHit(gs, dmg)
        return `칼날 파편 ${throws}발 투척`
      }
      case 'scabbard': {
        // 트리플: 칼날 파편 4장(+강화)을 손에 생성한다.
        let made = 0
        for (let i = 0; i < 4 + bonus; i++) {
          if (!c.hasHandRoom()) break
          c.addHandCard(DropSystem.makeCard('blade-shard'))
          made++
        }
        return made > 0 ? `칼날 파편 +${made}` : '손패 가득 참'
      }
      case 'sacrifice-shield': {
        // 자해는 selfDamageFor에서 처리. 방패 획득만 여기서 적용.
        const shielded = c.addShield(7 + bonus)
        return `자해 2 · 방패 +${shielded}`
      }
      case 'sweep':
        return HandSystem.clearSingleCellWebTraps(gs)
      case 'hand-mirror':
        // 복제 로직은 useSingle에서 chain.sequence를 직접 읽어 처리한다.
        return HandSystem.damageTargetEnemyByAtk(gs, target, bonus)
      case 'chandelier':
        // 처치 발생 시 index.ts가 200ms 딜레이로 동일 라운드를 반복 실행한다(chandelierRepeat 참조).
        return HandSystem.damageEnemies(gs, 'field', Math.floor(1 * c.damage) + 2 + bonus)
      case 'bonfire':
        // 처치 발생 시 회복은 index.ts가 bonfireHealOnKill로 처리한다.
        return HandSystem.damageTargetEnemy(gs, target, Math.floor(3 * c.damage) + 3 + bonus)
      case 'teapot':
        // 첫 타격만 여기서 실행. 나머지는 index.ts가 200ms 딜레이로 순차 실행한다(teapotExtraHits 참조).
        return HandSystem.damageTargetEnemy(gs, target, Math.floor(3 * c.damage) + bonus)
      case 'teacup': {
        const count = HandSystem.countFieldEnemies(gs)
        // 강화 1회당 승수 +1 (3+bonus 배).
        const healed = c.heal(count * (3 + bonus))
        return `트리플 체력 +${healed}`
      }
      case 'top-hat': {
        if (!target) return '이동할 카드 없음'
        // 전방 1칸 카드를 보물상자로 변환한 뒤 레인 맨 뒤로 순환 이동한다.
        const treasure = HandSystem.makeRecipeTreasure()
        HandSystem.rotateFrontToBack(gs, target.laneIndex, treasure)
        return `${target.card.name} 보물상자 변환 후 맨 뒤로 이동`
      }
      case 'slash': {
        // 즉사: 보스는 면역(저항 메시지만 반환하고 제거하지 않는다).
        const t = target ?? HandSystem.findFirstOnField(gs, [CardType.ENEMY, CardType.BOSS])
        if (!t || (t.card.type !== CardType.ENEMY && t.card.type !== CardType.BOSS))
          return '대상 적 없음'
        if (t.card.type === CardType.BOSS) return `${t.card.name} 저항`
        gs.removeCardFromRow(t.card, t.distance)
        return `${t.card.name} 즉사`
      }
      case 'shackles': {
        // 즉시 1턴 흐름은 simulatedBattlePhases=1로 index.ts에 위임한다.
        const shielded = c.addShield(5 + bonus)
        const healed = c.heal(5 + bonus)
        return `방패 +${shielded} · 체력 +${healed}`
      }
      case 'candle-tome': {
        const dmgPerEnemy = Math.floor(c.damage) + bonus
        HandSystem.damageEnemies(gs, 'field', dmgPerEnemy)
        const enemyCount = HandSystem.countFieldEnemies(gs)
        const shielded = c.addShield(enemyCount * 3 + bonus)
        return `트리플 전체 피해 ${dmgPerEnemy} · 필드 적 ${enemyCount}마리 → 방패 +${shielded}`
      }
      case 'sword-and-shield': {
        const dmg = HandSystem.damageTargetEnemy(gs, target, Math.floor(2 * c.damage) + 3 + bonus)
        const shielded = c.addShield(4 + bonus)
        return `트리플 ${dmg} · 방패 +${shielded}`
      }
      case 'watering-can': {
        if (!target || target.card.type !== CardType.FLOWER) return '꽃 대상 없음'
        const grew = target.card.growFlowerValueOnly(4 + bonus)
        return grew ? `트리플 ${target.card.name} 성장 → 수확값 +${4 + bonus}` : '씨앗은 성장 불가'
      }
      case 'garden-scissors':
        return HandSystem.applyGardenScissorsAll(gs)
      case 'ritual-candle': {
        // 트리플은 자해 1(selfDamageFor) 후 손패 2장 드로우.
        const count = 2 + bonus
        let gained = 0
        for (let i = 0; i < count; i++) {
          if (!c.hasHandRoom()) break
          c.addHandCard(DropSystem.generateDrop())
          gained++
        }
        return gained > 0 ? `자해 1 · 랜덤 손패 +${gained}` : '자해 1 · 손패 가득 참'
      }
      case 'black-candle':
        // 트리플: 자해 4(selfDamageFor), 카운터 +6(HandUseResult), 복귀(use()). 피해 누적.
        return HandSystem.applyBlackCandle(gs, target, 6, 6)
      case 'needle': {
        // 자해 2는 selfDamageFor, 처치 회복은 needleHealOnKill. 무작위 대상에 3발 연속 타격.
        const dmg = Math.floor(0.5 * c.damage) + 1 + bonus
        for (let i = 0; i < 3; i++) HandSystem.damageRandomFieldEnemy(gs, dmg)
        return `자해 2 · 바늘 3발 (0.5공+1)피해`
      }
      case 'voodoo-doll': {
        // 자해 2는 selfDamageFor. 트리플은 필드 전체 보물 수확 + 함정 제거.
        const harvested = HandSystem.collectAllTreasures(gs, c)
        const cleared = HandSystem.clearAllOfTypes(gs, [CardType.TRAP])
        return `자해 2 · ${harvested} · 함정 ${cleared}장 제거`
      }
      case 'guillotine':
        // 자해 10은 selfDamageFor. 필드 전체 적에게 (3.0공+8) 확정 피해.
        return HandSystem.damageEnemies(gs, 'field', Math.floor(3 * c.damage) + 8 + bonus)
    }
  }

  /** Scan the hand for runs of three consecutive same-defId cards. */
  /** 연속 동일 비합체 3장이 있어 자동 합성이 대기 중인지(모델 변경 없이) 확인한다.
   *  UI가 이동/낙하 연출 뒤 합성 비트를 분리할지 판단하는 데 쓴다. */
  static hasPendingAutoMerge(character: Character): boolean {
    const hand = character.hand
    for (let i = 0; i + 2 < hand.length; i++) {
      const a = hand[i]
      const b = hand[i + 1]
      const c = hand[i + 2]
      if (!a || !b || !c) continue
      if (a.merged || b.merged || c.merged) continue
      // 탐욕의 동전은 합성되지 않는 찌꺼기 카드라 트리플 대기 판정에서 제외한다.
      if (a.defId === 'greed-coin') continue
      if (a.defId === b.defId && b.defId === c.defId) return true
    }
    return false
  }

  static runAutoMerges(character: Character): string[] {
    const messages: string[] = []
    let didChange = true
    let safety = 32
    while (didChange && safety-- > 0) {
      didChange = false
      const hand = character.hand
      for (let i = 0; i + 2 < hand.length; i++) {
        const a = hand[i]
        const b = hand[i + 1]
        const c = hand[i + 2]
        if (!a || !b || !c) continue
        // Already-merged cards do not stack into another merged card; otherwise
        // a flood of duplicates could chain into massive auto-effects.
        if (a.merged || b.merged || c.merged) continue
        // 탐욕의 동전은 트리플 합성되지 않는다 — 손패를 갉아먹는 찌꺼기로 남는다.
        if (a.defId === 'greed-coin') continue
        if (a.defId === b.defId && b.defId === c.defId) {
          const def = getHandCardDef(a.defId)
          // Splice 3 → 1 merged card at slot i.
          hand.splice(i, 3, {
            uid: `${a.defId}-merged-${a.uid}`,
            defId: a.defId,
            merged: true,
            // Keep the exact consumed instance ids on the merged card.
            // The UI uses them while the card is newly rendered to pull
            // previous DOM rects and move upper cards into the lower slot.
            mergeSourceUids: [a.uid, b.uid, c.uid],
          })
          messages.push(`${def.name} ×3 자동 합성`)
          didChange = true
          break
        }
      }
    }
    return messages
  }

  /** Validate per-card targeting rules before consuming the hand card. */
  private static isValidTarget(
    def: HandCardDefinition,
    target: HandTarget | undefined,
    isMerged: boolean
  ): boolean {
    // Some triple effects become broad field effects and no longer need the
    // single-card target used by the base effect.
    const rule = isMerged ? def.targeting.triple : def.targeting.base
    if (rule.selection !== 'target') return true
    if (!target) return false
    return HandSystem.targetMatchesRule(rule, target)
  }

  /** Check a selected board card against the shared hand-card targeting table. */
  private static targetMatchesRule(rule: HandEffectTargeting, target: HandTarget): boolean {
    if (rule.zone === 'front' && target.distance !== 0) return false
    if (rule.zone === 'waiting' && target.distance === 0) return false
    if (rule.zone !== 'front' && rule.zone !== 'waiting' && rule.zone !== 'field') return false

    // 폭 제한: 지정된 maxSpan(칸=groupCount)을 넘는 카드는 대상에서 제외한다(키틴 2칸/3칸 분기).
    if (rule.maxSpan != null && target.card.groupCount > rule.maxSpan) return false

    // 보스는 5번째 카드 종류지만 적 양식을 그대로 따라가 손패 적 타겟팅에도 매칭된다.
    if (rule.filter === 'enemy') return target.card.type === CardType.ENEMY || target.card.type === CardType.BOSS
    if (rule.filter === 'trap') return target.card.type === CardType.TRAP
    if (rule.filter === 'spore') {
      // 성수 전용 필터: 일반 함정/폭탄은 두고 번식 포자만 대상으로 삼는다.
      return target.card.type === CardType.TRAP && target.card.trapKind === 'spore'
    }
    if (rule.filter === 'treasure') return target.card.type === CardType.TREASURE
    if (rule.filter === 'enemy-or-treasure') {
      return target.card.type === CardType.ENEMY || target.card.type === CardType.BOSS || target.card.type === CardType.TREASURE
    }
    // 부두 인형: 보물(수확) 또는 함정(제거) 어느 쪽이든 선택 가능.
    if (rule.filter === 'trap-or-treasure')
      return target.card.type === CardType.TRAP || target.card.type === CardType.TREASURE
    if (rule.filter === 'turn-timer') return HandSystem.isTurnTimerCard(target.card)
    if (rule.filter === 'hazard')
      return target.card.type === CardType.TRAP || target.card.isFrozen()
    if (rule.filter === 'flower')
      return target.card.type === CardType.FLOWER && target.card.flowerKind !== 'seed'
    if (rule.filter === 'flower-or-monsterflower') {
      if (target.card.type === CardType.FLOWER) return true
      return target.card.type === CardType.ENEMY && target.card.specialEnemyKind === 'monsterFlower'
    }
    if (rule.filter === 'any') return true
    return false
  }

  /** Deal damage to a chosen field enemy/boss, or to the first enemy-like card for merged auto-use. */
  private static damageTargetEnemy(
    gs: GameState,
    target: HandTarget | undefined,
    amount: number
  ): string {
    // BOSS도 적과 같은 양식의 5번째 카드 종류이므로 손패 적 타겟팅이 동일하게 닿는다.
    const actualTarget = target ?? HandSystem.findFirstOnField(gs, [CardType.ENEMY, CardType.BOSS])
    if (
      !actualTarget ||
      (actualTarget.card.type !== CardType.ENEMY && actualTarget.card.type !== CardType.BOSS)
    )
      return '대상 적 없음'
    actualTarget.card.takeDamage(amount)
    if (actualTarget.card.getHealth() <= 0) {
      // 보스는 lanes에 그대로 두고 격파 시퀀스(흔들→갈라짐→펑→흐릿 확대)가 element를
      // 그대로 잡아 시각화한 뒤 직접 정리한다. 일반 적은 즉시 제거.
      if (actualTarget.card.type !== CardType.BOSS) {
        gs.removeCardFromRow(actualTarget.card, actualTarget.distance)
      }
      return `${actualTarget.card.name} 피해 ${amount}로 처치`
    }
    return `${actualTarget.card.name} 피해 ${amount}`
  }

  /** Damage enemies/boss in either the whole field or only the active front row. */
  private static damageEnemies(gs: GameState, scope: 'front' | 'field', amount: number): string {
    const seen = new Set<Card>()
    let hit = 0
    let defeated = 0
    for (let lane = 0; lane < gs.lanes.length; lane++) {
      const maxDistance = scope === 'front' ? 1 : LANE_DISTANCE_COUNT
      for (let d = 0; d < maxDistance; d++) {
        const card = gs.lanes[lane].getCardAtDistance(d)
        if (!card || seen.has(card)) continue
        if (card.type !== CardType.ENEMY && card.type !== CardType.BOSS) continue
        seen.add(card)
        card.takeDamage(amount)
        hit++
        if (card.getHealth() <= 0) {
          // 보스는 별도 격파 시퀀스가 lanes 정리를 담당한다(시퀀스 도중 element가
          // 사라지지 않도록). 일반 적은 즉시 lane에서 제거.
          if (card.type !== CardType.BOSS) {
            gs.removeCardFromRow(card, d)
          }
          defeated++
        }
      }
    }
    const scopeLabel = scope === 'front' ? '전방 적' : '필드 적'
    return `${scopeLabel} ${hit}체에 피해 ${amount}${defeated > 0 ? ` · ${defeated}체 처치` : ''}`
  }

  /** 칼날 파편 1발: 랜덤 살아있는 적 1체에게 dmg 풀피해 한 방. 처치 시 관통(세로열)·도탄(인접 레인,
   *  넘친 피해)을 발동하고, 칼날 폭풍 보유 시 전체 적 대상으로 전환한다. 파편 카드·칼날의 서가 공유한다.
   *  (제거/피해는 이 함수가 보드에 직접 반영하고, 애니메이션은 useSingle의 before/after diff가 잡는다.) */
  static throwBladeShardHit(gs: GameState, dmg: number): void {
    const c = gs.character
    // 칼날 폭풍: 한 적이 아니라 필드 전체 적을 동시에 벤다(관통/도탄은 이미 전체라 생략).
    if (c.hasRelic('blade-storm')) { HandSystem.damageEnemies(gs, 'field', dmg); return }
    const targets: { card: Card; lane: number; d: number }[] = []
    const seen = new Set<Card>()
    for (let lane = 0; lane < gs.lanes.length; lane++) {
      for (let d = 0; d < LANE_DISTANCE_COUNT; d++) {
        const card = gs.lanes[lane].getCardAtDistance(d)
        if (!card || seen.has(card)) continue
        if (card.type !== CardType.ENEMY && card.type !== CardType.BOSS) continue
        seen.add(card)
        targets.push({ card, lane, d })
      }
    }
    if (targets.length === 0) return
    const t = targets[Math.floor(Math.random() * targets.length)]
    const before = Math.max(0, t.card.getHealth())
    t.card.takeDamage(dmg)
    if (t.card.getHealth() > 0) return
    if (t.card.type !== CardType.BOSS) gs.removeCardFromRow(t.card, t.d)
    // 관통: 처치한 적의 세로열 나머지 적에게 dmg.
    if (c.hasRelic('pierce-shard')) HandSystem.damageLaneEnemies(gs, t.lane, dmg, t.card)
    // 도탄: 처치하고 넘친 피해를 인접 레인 적 1체에게 전이.
    const overkill = dmg - before
    if (c.hasRelic('ricochet') && overkill > 0) HandSystem.ricochetShard(gs, t.lane, overkill)
  }

  /** 관통: 지정 레인의 (exclude 제외) 모든 적/보스에게 dmg. */
  private static damageLaneEnemies(gs: GameState, lane: number, dmg: number, exclude: Card): void {
    for (let d = 0; d < LANE_DISTANCE_COUNT; d++) {
      const card = gs.lanes[lane].getCardAtDistance(d)
      if (!card || card === exclude) continue
      if (card.type !== CardType.ENEMY && card.type !== CardType.BOSS) continue
      card.takeDamage(dmg)
      if (card.getHealth() <= 0 && card.type !== CardType.BOSS) gs.removeCardFromRow(card, d)
    }
  }

  /** 도탄: 인접 레인(좌/우) 중 먼저 만난 적 1체에게 넘친 피해를 전이한다. */
  private static ricochetShard(gs: GameState, lane: number, dmg: number): void {
    for (const adj of [lane - 1, lane + 1]) {
      if (adj < 0 || adj >= gs.lanes.length) continue
      for (let d = 0; d < LANE_DISTANCE_COUNT; d++) {
        const card = gs.lanes[adj].getCardAtDistance(d)
        if (!card) continue
        if (card.type !== CardType.ENEMY && card.type !== CardType.BOSS) break
        card.takeDamage(dmg)
        if (card.getHealth() <= 0 && card.type !== CardType.BOSS) gs.removeCardFromRow(card, d)
        return // 한 적에게만 전이
      }
    }
  }

  /** 폭죽: 총 피해를 필드 적/보스에게 1점씩 무작위로 쪼개 분배한다.
   *  한 적에게 여러 점이 몰릴 수도, 여러 적에게 흩어질 수도 있다. */
  private static distributeDamageAmongEnemies(gs: GameState, total: number): string {
    // 살아 있는 적/보스 카드를 (대표 distance와 함께) 고유하게 모은다.
    const living: { card: Card; distance: number }[] = []
    const seen = new Set<Card>()
    for (let lane = 0; lane < gs.lanes.length; lane++) {
      for (let d = 0; d < LANE_DISTANCE_COUNT; d++) {
        const card = gs.lanes[lane].getCardAtDistance(d)
        if (!card || seen.has(card)) continue
        if (card.type !== CardType.ENEMY && card.type !== CardType.BOSS) continue
        seen.add(card)
        living.push({ card, distance: d })
      }
    }
    if (living.length === 0) return '대상 적 없음'

    let defeated = 0
    for (let i = 0; i < total && living.length > 0; i++) {
      const pickIndex = Math.floor(Math.random() * living.length)
      const entry = living[pickIndex]
      entry.card.takeDamage(1)
      if (entry.card.getHealth() <= 0) {
        // 보스는 lanes에 남겨 격파 시퀀스가 정리한다. 일반 적은 즉시 제거하고 후보에서 뺀다.
        if (entry.card.type !== CardType.BOSS) {
          gs.removeCardFromRow(entry.card, entry.distance)
        }
        living.splice(pickIndex, 1)
        defeated++
      }
    }
    return `폭죽: 적들에게 피해 ${total} 분배${defeated > 0 ? ` · ${defeated}체 처치` : ''}`
  }

  /** 화염의 서: 공격력 비례 성장 공격. 누적 스택 n 기준 단일 피해 = floor((0.5+0.25n)×공) + (1+n).
   *  단일: inc=1, mul=1. 트리플: inc=2, mul=2 → 단일 공식의 2배 피해 + 스택 2배 속도.
   *  표시 수치는 GameBoardRenderer.enhancedHandCardDescription과 같은 식을 유지해야 한다. */
  private static applyBookOfFlames(
    gs: GameState,
    target: HandTarget | undefined,
    atk: number,
    increment: number,
    multiplier = 1
  ): string {
    const n = gs.enhancements.bookOfFlamesBonus ?? 0
    const amount = Math.floor((0.5 + 0.25 * n) * atk * multiplier) + (1 + n) * multiplier
    const result = HandSystem.damageTargetEnemy(gs, target, amount)
    gs.enhancements.bookOfFlamesBonus = n + increment
    return `${result} · 화염의 서 성장 +${increment}(누적 ${gs.enhancements.bookOfFlamesBonus})`
  }

  /** 검은 양초: book-of-flames와 동일하게 base 피해 후 누적 보너스를 increment만큼 증가. */
  private static applyBlackCandle(
    gs: GameState,
    target: HandTarget | undefined,
    base: number,
    increment: number
  ): string {
    const n = gs.enhancements.blackCandleBonus ?? 0
    const amount = base + n
    const result = HandSystem.damageTargetEnemy(gs, target, amount)
    gs.enhancements.blackCandleBonus = n + increment
    return `${result} · 검은 양초 피해 영구 +${increment}(누적 ${gs.enhancements.blackCandleBonus})`
  }

  /** Destroy one random enemy/boss from the active row. */
  private static destroyRandomFrontEnemy(gs: GameState): string {
    const enemies: { card: Card; distance: number }[] = []
    const seen = new Set<Card>()
    for (const lane of gs.lanes) {
      const card = lane.getCardAtDistance(0)
      if (!card || seen.has(card)) continue
      // 보스는 레시피 즉사 대상에서 제외 — 보스 면역 처리는 index.ts에서 저항 연출 담당.
      if (card.type !== CardType.ENEMY) continue
      seen.add(card)
      enemies.push({ card, distance: 0 })
    }
    if (enemies.length === 0) return '전방 적 없음'
    const pick = enemies[Math.floor(Math.random() * enemies.length)]
    gs.removeCardFromRow(pick.card, pick.distance)
    return `${pick.card.name} 처치`
  }

  /** Create a one-cell treasure card for recipe conversions. */
  private static makeRecipeTreasure(): Card {
    return new Card(
      `treasure-recipe-${Date.now()}-${Math.random()}`,
      CardType.TREASURE,
      '작은 상자',
      '1 item reward chest'
    )
  }

  /** Replace one unique field card with a treasure while preserving its row width. */
  private static replaceCardWithTreasure(gs: GameState, source: Card, distance: number): void {
    const treasure = HandSystem.makeRecipeTreasure()
    treasure.groupCount = Math.max(1, source.groupCount)
    for (let laneIndex = 0; laneIndex < gs.lanes.length; laneIndex++) {
      if (gs.lanes[laneIndex].getCardAtDistance(distance) === source) {
        gs.lanes[laneIndex].setCardAtDistance(distance, treasure)
      }
    }
  }

  /** MVP hazard conversion maps curse/mold wording to traps and frozen cards. */
  private static convertRandomHazardToTreasure(gs: GameState): string {
    const candidates: { card: Card; distance: number }[] = []
    const seen = new Set<Card>()
    for (const lane of gs.lanes) {
      for (let d = 0; d < LANE_DISTANCE_COUNT; d++) {
        const card = lane.getCardAtDistance(d)
        if (!card || seen.has(card)) continue
        if (card.type === CardType.TRAP || card.isFrozen()) {
          seen.add(card)
          candidates.push({ card, distance: d })
        }
      }
    }
    if (candidates.length === 0) return '변환할 함정/저주/곰팡이 없음'
    const pick = candidates[Math.floor(Math.random() * candidates.length)]
    HandSystem.replaceCardWithTreasure(gs, pick.card, pick.distance)
    return `${pick.card.name} 보물상자로 변환`
  }

  /** Turn one non-treasure waiting-line cell into a chest, including empty cells. */
  private static convertRandomWaitingSlotToTreasure(gs: GameState): string {
    const candidates: { laneIndex: number; distance: number; card: Card | null }[] = []
    for (let laneIndex = 0; laneIndex < gs.lanes.length; laneIndex++) {
      for (let d = 1; d < LANE_DISTANCE_COUNT; d++) {
        const card = gs.lanes[laneIndex].getCardAtDistance(d)
        if (card?.type === CardType.TREASURE) continue
        candidates.push({ laneIndex, distance: d, card })
      }
    }
    if (candidates.length === 0) return '대기라인에 변환할 칸 없음'
    const pick = candidates[Math.floor(Math.random() * candidates.length)]
    gs.lanes[pick.laneIndex].setCardAtDistance(pick.distance, HandSystem.makeRecipeTreasure())
    return pick.card ? `${pick.card.name} 보물상자로 변환` : '빈 대기칸을 보물상자로 변환'
  }

  /** Remove every active-row card, counting unique card instances once. */
  private static clearFrontCards(gs: GameState): string {
    const seen = new Set<Card>()
    let cleared = 0
    for (let lane = 0; lane < gs.lanes.length; lane++) {
      const card = gs.lanes[lane].getCardAtDistance(0)
      if (!card || seen.has(card)) continue
      // 보스는 전방 소멸 레시피에서 면역 — 저항 연출은 index.ts 레시피 루프에서 재생.
      if (card.type === CardType.BOSS) continue
      seen.add(card)
      gs.removeCardFromRow(card, 0)
      cleared++
    }
    return `전방 ${cleared}장 제거`
  }

  /** Open only treasures that are still waiting behind the active row. */
  private static collectWaitingTreasures(gs: GameState, character: Character): string {
    const treasures: { card: Card; distance: number }[] = []
    const seen = new Set<Card>()
    for (let lane = 0; lane < gs.lanes.length; lane++) {
      for (let d = 1; d < LANE_DISTANCE_COUNT; d++) {
        const card = gs.lanes[lane].getCardAtDistance(d)
        if (!card || seen.has(card) || card.type !== CardType.TREASURE) continue
        seen.add(card)
        treasures.push({ card, distance: d })
      }
    }
    let gained = 0
    for (const treasure of treasures) {
      gained += HandSystem.awardTreasureDrops(character, treasure.card)
      gs.removeCardFromRow(treasure.card, treasure.distance)
    }
    HandSystem.runAutoMerges(character)
    return `대기 보물 ${treasures.length}개 획득: 손패 ${gained}장`
  }

  /** Open one random treasure chest and convert its width into item drops. */
  /** 바늘: 필드의 살아있는 적/보스 중 무작위 1체에게 amount 피해. 처치 시 제거(회복은 needleHealOnKill). */
  private static damageRandomFieldEnemy(gs: GameState, amount: number): string {
    const living: { card: Card; distance: number }[] = []
    const seen = new Set<Card>()
    for (let lane = 0; lane < gs.lanes.length; lane++) {
      for (let d = 0; d < LANE_DISTANCE_COUNT; d++) {
        const card = gs.lanes[lane].getCardAtDistance(d)
        if (!card || seen.has(card)) continue
        if (card.type !== CardType.ENEMY && card.type !== CardType.BOSS) continue
        seen.add(card)
        living.push({ card, distance: d })
      }
    }
    if (living.length === 0) return '대상 적 없음'
    const pick = living[Math.floor(Math.random() * living.length)]
    pick.card.takeDamage(amount)
    // 보스는 별도 격파 시퀀스가 lanes 정리를 담당하므로 즉시 제거하지 않는다.
    if (pick.card.getHealth() <= 0 && pick.card.type !== CardType.BOSS) {
      gs.removeCardFromRow(pick.card, pick.distance)
    }
    return `랜덤 적에게 ${amount}피해`
  }

  /** 부두 인형(단일): 선택 1칸의 보물을 수확하거나 함정을 제거한다(자해는 selfDamageFor). */
  private static applyVoodooDoll(
    gs: GameState,
    character: Character,
    target: HandTarget | undefined
  ): string {
    if (!target) return '자해 2 · 대상 없음'
    if (target.card.type === CardType.TREASURE) {
      const gained = HandSystem.awardTreasureDrops(character, target.card)
      for (let d = 0; d < LANE_DISTANCE_COUNT; d++) gs.removeCardFromRow(target.card, d)
      HandSystem.runAutoMerges(character)
      return `자해 2 · ${target.card.name} 수확: 손패 ${gained}장`
    }
    if (target.card.type === CardType.TRAP) {
      gs.removeCardFromRow(target.card, target.distance)
      return `자해 2 · ${target.card.name} 제거`
    }
    return '자해 2 · 대상 없음'
  }

  private static collectRandomTreasure(gs: GameState, character: Character): string {
    const treasures = HandSystem.collectAllOfType(gs, CardType.TREASURE)
    if (treasures.length === 0) return '보물상자 없음'
    const pick = treasures[Math.floor(Math.random() * treasures.length)]
    const gained = HandSystem.awardTreasureDrops(character, pick)
    for (let d = 0; d < LANE_DISTANCE_COUNT; d++) gs.removeCardFromRow(pick, d)
    return `${pick.name} 획득: 손패 ${gained}장`
  }

  /** Open every treasure currently on the 3×3 field. */
  private static collectAllTreasures(gs: GameState, character: Character): string {
    const treasures = HandSystem.collectAllOfType(gs, CardType.TREASURE)
    let gained = 0
    for (const treasure of treasures) {
      gained += HandSystem.awardTreasureDrops(character, treasure)
      for (let d = 0; d < LANE_DISTANCE_COUNT; d++) gs.removeCardFromRow(treasure, d)
    }
    HandSystem.runAutoMerges(character)
    return `트리플 보물 ${treasures.length}개 획득: 손패 ${gained}장`
  }

  /** Award item drops based on chest width and kind, matching ActionSystem. */
  private static awardTreasureDrops(character: Character, treasure: Card): number {
    const safeSpan = Math.max(1, Math.min(3, treasure.groupCount))
    const dropCount = treasure.treasureKind === 'goldenChest'
      ? [3, 8, 15][safeSpan - 1]
      : safeSpan === 1 ? 1 : safeSpan === 2 ? 3 : 5
    let gained = 0
    for (let i = 0; i < dropCount; i++) {
      if (!character.hasHandRoom()) break
      // 보물상자 개봉은 일반 드롭 풀에 treasure-only 동전을 추가한다.
      character.addHandCard(DropSystem.generateDrop('treasure'))
      gained++
    }
    HandSystem.runAutoMerges(character)
    return gained
  }

  /** Cards with per-turn behavior can be stopped by wax: active enemies, volatile
   *  treasures, bombs/spores, and bloomed flowers all own a timer-like beat. */
  private static isTurnTimerCard(card: Card): boolean {
    if (card.type === CardType.ENEMY) return true
    if (card.type === CardType.BOSS) return true
    if (card.type === CardType.TREASURE) return true
    if (card.type === CardType.TRAP) return card.trapKind === 'bomb' || card.trapKind === 'spore'
    if (card.type === CardType.FLOWER) return card.flowerKind !== 'seed'
    return false
  }

  /** Apply wax hardening to a selected front card. 보스도 굳힐 수 있다(즉사는 면역이나 굳음은 적용). */
  private static freezeTarget(target: HandTarget | undefined, turns: number): string {
    if (!target) return '굳힐 대상 없음'
    target.card.freeze(turns)
    return `${target.card.name} ${turns}턴 굳음`
  }

  /** Freeze one random front card that has a turn timer. 재활용 유물이 태그 반응으로 호출한다.
   *  대상이 없으면 null. 굳힌 카드를 돌려줘 호출부가 로그/FX에 쓴다. */
  static freezeRandomFrontTimerCard(gs: GameState, turns: number): Card | null {
    const candidates: Card[] = []
    const seen = new Set<Card>()
    for (const lane of gs.lanes) {
      const card = lane.getCardAtDistance(0)
      if (!card || seen.has(card)) continue
      if (!HandSystem.isTurnTimerCard(card) || card.isFrozen()) continue
      seen.add(card)
      candidates.push(card)
    }
    if (candidates.length === 0) return null
    const pick = candidates[Math.floor(Math.random() * candidates.length)]
    pick.freeze(turns)
    return pick
  }

  /** Apply wax hardening to every front card with a turn timer(보스 포함). */
  private static freezeFrontCards(gs: GameState, turns: number): string {
    const seen = new Set<Card>()
    let count = 0
    for (const lane of gs.lanes) {
      const card = lane.getCardAtDistance(0)
      if (!card || seen.has(card)) continue
      if (!HandSystem.isTurnTimerCard(card)) continue
      seen.add(card)
      card.freeze(turns)
      count++
    }
    return `전방 ${count}장 ${turns}턴 굳음`
  }

  /** Remove up to `count` random spore traps; 성수 no longer cleanses other hazards. */
  private static cleanseRandomSpores(gs: GameState, count: number, prefix = ''): string {
    const candidates = HandSystem.collectAllOfType(gs, CardType.TRAP).filter(
      (card) => card.trapKind === 'spore'
    )
    let cleansed = 0
    while (candidates.length > 0 && cleansed < count) {
      const pickIndex = Math.floor(Math.random() * candidates.length)
      const [card] = candidates.splice(pickIndex, 1)
      // removeCardFromRow clears every lane that references the same grouped
      // spore, so a 2/3칸 포자군 still disappears as one selected card.
      for (let d = 0; d < LANE_DISTANCE_COUNT; d++) gs.removeCardFromRow(card, d)
      cleansed++
    }
    return `${prefix}포자 ${cleansed}장 제거`
  }

  /** Triple 성수 removes every spore while preserving webs, bombs, and frozen cards. */
  private static cleanseAllSpores(gs: GameState): string {
    const spores = HandSystem.collectAllOfType(gs, CardType.TRAP).filter(
      (card) => card.trapKind === 'spore'
    )
    for (const card of spores) {
      // Grouped spores share one Card instance, so this clears the whole group.
      for (let d = 0; d < LANE_DISTANCE_COUNT; d++) gs.removeCardFromRow(card, d)
    }
    return `트리플 전체 포자 ${spores.length}장 제거`
  }

  /** Remove the selected front trap. */
  private static removeTargetTrap(gs: GameState, target: HandTarget | undefined): string {
    if (!target || target.card.type !== CardType.TRAP) return '제거할 전방 함정 없음'
    gs.removeCardFromRow(target.card, target.distance)
    return `${target.card.name} 제거`
  }

  /** Find the first matching card anywhere on the 3×3 field. */
  private static findFirstOnField(
    gs: GameState,
    types: CardType[]
  ): { card: Card; laneIndex: number; distance: number } | null {
    for (let laneIndex = 0; laneIndex < gs.lanes.length; laneIndex++) {
      for (let distance = 0; distance < LANE_DISTANCE_COUNT; distance++) {
        const card = gs.lanes[laneIndex].getCardAtDistance(distance)
        if (card && types.includes(card.type)) return { card, laneIndex, distance }
      }
    }
    return null
  }

  private static collectAllOfType(gs: GameState, type: CardType): Card[] {
    const out: Card[] = []
    const seen = new Set<Card>()
    for (const lane of gs.lanes) {
      for (let d = 0; d < LANE_DISTANCE_COUNT; d++) {
        const card = lane.getCardAtDistance(d)
        if (!card || seen.has(card)) continue
        if (card.type === type) {
          seen.add(card)
          out.push(card)
        }
      }
    }
    return out
  }

  /** 청소: groupCount === 1인 거미줄(web) 함정만 필드에서 제거한다.
   *  2·3칸 거미줄은 플레이어에게 치명적이라 의도적으로 제외한다. */
  private static clearSingleCellWebTraps(gs: GameState): string {
    const seen = new Set<Card>()
    let cleared = 0
    for (const lane of gs.lanes) {
      for (let d = 0; d < LANE_DISTANCE_COUNT; d++) {
        const card = lane.getCardAtDistance(d)
        if (!card || seen.has(card)) continue
        if (card.type !== CardType.TRAP || card.trapKind !== 'web' || card.groupCount !== 1) continue
        seen.add(card)
        gs.removeCardFromRow(card, d)
        cleared++
      }
    }
    return cleared > 0 ? `1칸 거미줄 ${cleared}장 제거` : '제거할 1칸 거미줄 없음'
  }

  /** 손거울: 대상 적의 현재 공격력만큼 피해를 입힌다. */
  private static damageTargetEnemyByAtk(
    gs: GameState,
    target: HandTarget | undefined,
    bonus: number
  ): string {
    const t = target ?? HandSystem.findFirstOnField(gs, [CardType.ENEMY, CardType.BOSS])
    if (!t || (t.card.type !== CardType.ENEMY && t.card.type !== CardType.BOSS))
      return '대상 적 없음'
    const amount = Math.max(0, t.card.getDamage() + bonus)
    return HandSystem.damageTargetEnemy(gs, t, amount)
  }

  private static clearAllOfTypes(gs: GameState, types: CardType[]): number {
    const seen = new Set<Card>()
    let count = 0
    for (const lane of gs.lanes) {
      for (let d = 0; d < LANE_DISTANCE_COUNT; d++) {
        const card = lane.getCardAtDistance(d)
        if (!card || seen.has(card)) continue
        if (types.includes(card.type)) {
          seen.add(card)
          gs.removeCardFromRow(card, d)
          count++
        }
      }
    }
    return count
  }

  /** 끓는 분노: 전방 모든 일반 적을 처치한다. 보스는 즉사 면역으로 제외한다. */
  private static destroyAllFrontEnemies(gs: GameState): number {
    const seen = new Set<Card>()
    let killed = 0
    for (const lane of gs.lanes) {
      const card = lane.getCardAtDistance(0)
      if (!card || seen.has(card)) continue
      if (card.type !== CardType.ENEMY) continue
      seen.add(card)
      gs.removeCardFromRow(card, 0)
      killed++
    }
    return killed
  }

  /** 필드에 살아있는 적/보스의 고유 수를 반환한다(주전자·찻잔에서 타격 횟수/회복량 계산에 사용). */
  private static countFieldEnemies(gs: GameState): number {
    const seen = new Set<Card>()
    for (const lane of gs.lanes) {
      for (let d = 0; d < LANE_DISTANCE_COUNT; d++) {
        const card = lane.getCardAtDistance(d)
        if (!card || seen.has(card)) continue
        if (card.type === CardType.ENEMY || card.type === CardType.BOSS) seen.add(card)
      }
    }
    return seen.size
  }

  /** 신사모: 선택 레인의 d0 카드를 맨 뒤(d2)로 순환 이동(d1→d0, d2→d1, d0→d2).
   *  replacement가 있으면 원본 d0은 버리고 새 카드(보물상자)를 d2에 배치한다. */
  private static rotateFrontToBack(gs: GameState, laneIndex: number, replacement?: Card | null): void {
    const lane = gs.lanes[laneIndex]
    const d0 = lane.getCardAtDistance(0)
    const d1 = lane.getCardAtDistance(1)
    const d2 = lane.getCardAtDistance(2)
    lane.setCardAtDistance(0, d1)
    lane.setCardAtDistance(1, d2)
    lane.setCardAtDistance(2, replacement !== undefined ? replacement : d0)
  }

  /** 샹들리에 반복 라운드: 필드 전체 적에게 amount 피해를 입히고 제거된 카드 목록을 반환한다.
   *  index.ts가 처치 발생 시 200ms 딜레이 후 이 메서드를 재호출해 연속 빠른 재실행을 구현한다. */
  static applyChandelierRound(gs: GameState, amount: number): { removedFieldCards: RemovedFieldCard[] } {
    const before = HandSystem.snapshotFieldCards(gs)
    HandSystem.damageEnemies(gs, 'field', amount)
    const after = HandSystem.snapshotFieldCards(gs)
    const removedFieldCards: RemovedFieldCard[] = []
    for (const [id, type] of before.entries()) {
      if (!after.has(id)) removedFieldCards.push({ cardId: id, type })
    }
    return { removedFieldCards }
  }

  /** 주전자 단회 타격: target 적에게 amount 피해를 입히고 제거 여부와 카드 목록을 반환한다.
   *  index.ts가 200ms 딜레이로 이 메서드를 반복 호출해 빠른 연속 타격을 구현한다. */
  static applyTeapotHit(
    gs: GameState,
    target: HandTarget,
    amount: number
  ): { removedFieldCards: RemovedFieldCard[]; targetKilled: boolean } {
    const before = HandSystem.snapshotFieldCards(gs)
    HandSystem.damageTargetEnemy(gs, target, amount)
    const after = HandSystem.snapshotFieldCards(gs)
    const removedFieldCards: RemovedFieldCard[] = []
    for (const [id, type] of before.entries()) {
      if (!after.has(id)) removedFieldCards.push({ cardId: id, type })
    }
    return { removedFieldCards, targetKilled: !after.has(target.card.id) }
  }

  /** 정원 가위 단일: 꽃은 ActionSystem.takeFlower와 동일한 종류별 보상을 적용하고,
   *  괴물꽃은 즉사시킨다. 캐모마일/금잔화 몫은 pendingFlowerHarvests에 기록해
   *  index.ts가 useSingle() 반환값(flowerHarvests)으로 이어받아 지급한다. */
  static applyGardenScissorsSingle(
    gs: GameState,
    target: HandTarget | undefined
  ): string {
    if (!target) return '대상 없음'
    const card = target.card
    if (card.type === CardType.FLOWER && card.flowerKind !== 'seed') {
      gs.removeCardFromRow(card, target.distance)
      HandSystem.harvestFlowerReward(gs.character, card)
      return `${card.name} 즉시 수확`
    }
    if (card.type === CardType.ENEMY && card.specialEnemyKind === 'monsterFlower') {
      gs.removeCardFromRow(card, target.distance)
      return `${card.name} 즉사`
    }
    return '꽃이나 괴물꽃 대상 필요'
  }

  /** 정원 가위 트리플: 필드 전체 꽃을 종류별 보상과 함께 수확하고 괴물꽃을 즉사시킨다. */
  static applyGardenScissorsAll(gs: GameState): string {
    const seen = new Set<Card>()
    let harvested = 0
    let killed = 0
    for (const lane of gs.lanes) {
      for (let d = 0; d < LANE_DISTANCE_COUNT; d++) {
        const card = lane.getCardAtDistance(d)
        if (!card || seen.has(card)) continue
        seen.add(card)
        if (card.type === CardType.FLOWER && card.flowerKind !== 'seed') {
          gs.removeCardFromRow(card, d)
          HandSystem.harvestFlowerReward(gs.character, card)
          harvested++
        } else if (card.type === CardType.ENEMY && card.specialEnemyKind === 'monsterFlower') {
          gs.removeCardFromRow(card, d)
          killed++
        }
      }
    }
    const parts: string[] = []
    if (harvested > 0) parts.push(`꽃 ${harvested}장 수확`)
    if (killed > 0) parts.push(`괴물꽃 ${killed}체 즉사`)
    return parts.length > 0 ? parts.join(' · ') : '대상 없음'
  }
}
